 🔹 NP1–NP10: Array Conversions & Basic Integration

In [1]:
### NP1. Create a NumPy array and convert it to a Pandas Series.
import numpy as np
import pandas as pd
array=np.array([10,20,30,40,50,60,70])
data=pd.Series(array , index=[1,2,3,4,5,6,7], name='roll_no')
print(data)

1    10
2    20
3    30
4    40
5    50
6    60
7    70
Name: roll_no, dtype: int64

In [2]:
### NP2. Convert a 2D NumPy array to a Pandas DataFrame.
arr_2D=np.array([[1,2,3],[4,5,6]])
print(arr_2D)
data_2d=pd.DataFrame(arr_2D, columns=['A','B','C'])
print("shape of the data_2d", data_2d.shape)
print(data_2d)

[[1 2 3]
 [4 5 6]]
shape of the data_2d (2, 3)
   A  B  C
0  1  2  3
1  4  5  6

In [3]:
### NP3. Generate a random dataset using NumPy and store it in a DataFrame.
np.random.seed(42)
data_2d=np.random.rand(3,14)
print(data_2d)
print()
data2=np.random.randint(low=5 , high=40 , size=(3,4))
print(data2)
store_dataframe= pd.DataFrame(data2 , columns=['present','absent', 'rollno','marks'])
print(store_dataframe)

[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
  0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
  0.83244264 0.21233911]
 [0.18182497 0.18340451 0.30424224 0.52475643 0.43194502 0.29122914
  0.61185289 0.13949386 0.29214465 0.36636184 0.45606998 0.78517596
  0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485 0.17052412 0.06505159 0.94888554
  0.96563203 0.80839735 0.30461377 0.09767211 0.68423303 0.44015249
  0.12203823 0.49517691]]

[[39 18 21  8]
 [ 6 10  8 33]
 [22 30 38 14]]
   present  absent  rollno  marks
0       39      18      21      8
1        6      10       8     33
2       22      30      38     14

In [4]:
### NP4. Perform element-wise operations using NumPy and Pandas.
print(np.sqrt(store_dataframe['marks']))

0    2.828427
1    5.744563
2    3.741657
Name: marks, dtype: float64

1. Using NumPy mean

np.mean(store_dataframe['marks'])

Passes the Pandas Series to NumPy.

NumPy computes the average.

Output is a scalar value.

2. Using Pandas mean

store_dataframe['marks'].mean()

Pandas' built-in method.

Usually the preferred and most readable approach.

3. Using NumPy on the underlying NumPy array

np.mean(store_dataframe['marks'].values)

.values extracts the NumPy array from the Series.

NumPy works directly on the array.

Often used when performing multiple NumPy operations.

In [5]:
### NP5. Apply `np.mean` on DataFrame columns.
print("=========using numpy mean================")
np_mean=np.mean(store_dataframe['marks'])
print(np_mean)
print("===========using dataframe mean============")
df_mean=store_dataframe['marks'].mean()
print(df_mean)
print("===============apply values func===========")
val=np.mean(store_dataframe['marks'].values)
print(val)

=========using numpy mean================
18.333333333333332
===========using dataframe mean============
18.333333333333332
===============apply values func===========
18.333333333333332

np.random.seed(42)

data_2d=np.random.rand(3,14)

print(data_2d)

print()

data2=np.random.randint(low=5 , high=40 , size=(3,4))

print(data2)

store_dataframe= pd.DataFrame(data2 , columns=['present','absent', 'rollno','marks'])

print(store_dataframe)

In [6]:
### NP6. Replace values using `np.where`.
store_dataframe['marks']=np.where(store_dataframe['marks'] >15 ,'high', 'low')
print(store_dataframe['marks'])

0     low
1    high
2     low
Name: marks, dtype: str

In [7]:
### NP7. Apply logarithmic transformation using `np.log`.
store_dataframe['absent']=np.log(store_dataframe['absent'])
print(store_dataframe['absent'])
print()

df=pd.DataFrame({
    'marks':[10,0,20,23,0]
})
#np.log(0) returns -inf:
#df_log0=np.log(df['marks'])
#print(df_log0)

#np.log1p(x) computes log(1+x) and handles zeros safely:
df_log1=np.log1p(df['marks'])
print(df_log1)

# warning occures because ===np.log1p() still cannot handle values less than -

0    2.890372
1    2.302585
2    3.401197
Name: absent, dtype: float64

0    2.397895
1    0.000000
2    3.044522
3    3.178054
4    0.000000
Name: marks, dtype: float64

In [8]:
### NP8. Apply square root transformation using `np.sqrt`.
#sqare root 
df['col_sqrt']=np.sqrt(df['marks'])
print(df['col_sqrt'])

#for appying negative values
df1=pd.DataFrame({
    'marks':[10,-90,20,-23,0]
})
print(np.clip(df1['marks'], 0 ,None))
#first cnvert negative value into positive then apply sqrt on it
print(np.sqrt(df['marks']))

0    3.162278
1    0.000000
2    4.472136
3    4.795832
4    0.000000
Name: col_sqrt, dtype: float64
0    10
1     0
2    20
3     0
4     0
Name: marks, dtype: int64
0    3.162278
1    0.000000
2    4.472136
3    4.795832
4    0.000000
Name: marks, dtype: float64

apply() processes each value in the absent column.

The lambda function computes np.log(x) for each value.

A new Series containing the logarithms is returned.

In [9]:
### NP9. Use NumPy functions inside `apply()`.
apply_fuc=store_dataframe['present'].apply(lambda x :np.log(x))
print(apply_fuc)

0    3.663562
1    1.791759
2    3.091042
Name: present, dtype: float64

In [10]:
### NP10. Perform broadcasting in a DataFrame using NumPy.
extract_val=store_dataframe['present'].values 
print(extract_val)

[39  6 22]

🔹 NP11–NP20: Data Filtering, Transformation & Statistics

In [11]:
student = pd.DataFrame({
    'present': np.random.randint(10, 31, 50),
    'absent': np.random.randint(0, 11, 50),
    'rollno': np.arange(101, 151),
    'marks': np.random.randint(35, 101, 50)
})

In [12]:
### NP11. Filter DataFrame rows using a NumPy boolean mask.
#print(store_dataframe)
mask=np.array(student['present']> 20)
print(mask)
filtered_data=student[mask]
print(filtered_data)
#print(student)

[False  True  True  True False  True False  True  True  True  True  True
  True  True False  True  True False False False False  True False False
  True  True False False False False False False False False False False
 False  True False False  True False False  True False False False False
 False  True]
    present  absent  rollno  marks
1        23       0     102     78
2        25       4     103     58
3        24       9     104     93
5        23       6     106     86
7        30       8     108     92
8        25       9     109     86
9        22       9     110     46
10       27       2     111     73
11       24       6     112     36
12       30       0     113     37
13       22       3     114     90
15       24       4     116     36
16       22       6     117     36
21       21      10     122     87
24       28       1     125     66
25       26       9     126     89
37       21       8     138     53
40       25       3     141     86
43       21       6     144     73
49       24       0     150     65

In [13]:
## NP12. Count non-zero values in a column using NumPy.
print(np.count_nonzero(student['absent'].values))
print(np.count_nonzero(student['absent'].values !=0))

45
45

In [14]:

### NP13. Find unique values using `np.unique`.
print(np.unique(student['absent']))
print(np.unique(student['present'],return_counts=True))
print(student['present'])

#np.unique() finds all unique values in the present column and,
#return_counts=True, also returns how many times each value appears.

[ 0  1  2  3  4  5  6  7  8  9 10]
(array([10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 30], dtype=int32), array([5, 1, 5, 1, 3, 3, 6, 4, 1, 1, 3, 3, 2, 4, 3, 1, 1, 1, 2]))
0     13
1     23
2     25
3     24
4     17
5     23
6     17
7     30
8     25
9     22
10    27
11    24
12    30
13    22
14    18
15    24
16    22
17    10
18    16
19    18
20    10
21    21
22    17
23    20
24    28
25    26
26    17
27    12
28    12
29    10
30    14
31    19
32    16
33    18
34    16
35    18
36    17
37    21
38    11
39    10
40    25
41    14
42    12
43    21
44    17
45    12
46    10
47    12
48    14
49    24
Name: present, dtype: int32

In [15]:
### NP14. Flatten DataFrame values to a 1D NumPy array.
print(student[['present' , 'absent']].values.flatten())

[13  2 23  0 25  4 24  9 17  6 23  6 17 10 30  8 25  9 22  9 27  2 24  6
 30  0 22  3 18  3 24  4 22  6 10  6 16 10 18  3 10  6 21 10 17  2 20  5
 28  1 26  9 17  8 12  4 12  5 10  3 14 10 19  9 16  6 18  8 16  6 18  0
 17  0 21  8 11 10 10  8 25  3 14  8 12  2 21  6 17  5 12  7 10 10 12  8
 14  4 24  0]

In [16]:
### NP15. Reshape a NumPy array before creating a DataFrame.
arr=np.arange(1,25).reshape(6,4)
print(arr)
rename=pd.DataFrame(arr,columns=['A','B','C','D'])
rename
#print(rename)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

    A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20
5  21  22  23  24

In [17]:
### NP16. Perform matrix multiplication using `np.dot`.
arr1=pd.DataFrame({
    'A' :[10,20] ,
    'B' : [30,40]})
arr2=pd.DataFrame({
    'C' : [50,60],
    'D' : [70,80]})
matrix_mul=np.dot(arr1 , arr2)
print(matrix_mul)

new_result=pd.DataFrame(
    matrix_mul , columns=['f','s'])
print(new_result)

[[2300 3100]
 [3400 4600]]
      f     s
0  2300  3100
1  3400  4600

In [18]:
### NP17. Normalize data using NumPy (Min-Max scaling).
arr=new_result['f'].values
print((arr-arr.min(axis=0))/ (arr.max(axis=0) - arr.min(axis=0)))

[0. 1.]

In [19]:
### NP18. Standardize data using Z-score with NumPy.
arr_mean=arr.mean(axis=0)
print("mean : ",arr_mean)
arr_std=arr.std(axis=0)
print("std : ",arr_std)
z_score=(arr - arr_mean) / arr_std
print("z_scoes : ",z_score)

# in one line
z=(arr-arr.mean(axis=0)) /arr.std(axis=0)
print(z)

mean :  2850.0
std :  550.0
z_scoes :  [-1.  1.]
[-1.  1.]

In [20]:
### NP19. Clip values using `np.clip`.
#np.clip() is used to limit (clip) values within a specified range.
print(np.clip(rename['A'].values , a_min=15 , a_max=20))
rename

[15 15 15 15 17 20]

    A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20
5  21  22  23  24

In [21]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', np.nan, 'David'],
    'Age': [20, np.nan, 22, 23],
    'Marks': [85, 90, np.nan, 88]
})

In [22]:
np.random.seed(42)
dg=np.random.rand(4, 6)
add_row=[1,3,2]
add_col=[1,3,2]
dg[add_row ,add_col]=np.nan
print(dg)
find_nan=np.isnan(dg)
find_mean=np.nanmean(dg)
dg[np.isnan(dg)]=np.nanmean(dg)
print(dg)

[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452]
 [0.05808361        nan 0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911        nan 0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289        nan 0.29214465 0.36636184]]
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452]
 [0.05808361 0.44649543 0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.44649543 0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289 0.44649543 0.29214465 0.36636184]]

In [23]:
### NP20. Handle missing values using pandas.
print(df.isna())
#filling from mean

print(df['Marks'].fillna(df['Marks'].mean()))

    Name    Age  Marks
0  False  False  False
1  False   True  False
2   True  False   True
3  False  False  False
0    85.000000
1    90.000000
2    87.666667
3    88.000000
Name: Marks, dtype: float64

🔹 NP21–NP30: Performance, Sorting & Statistical Analysis

In [24]:
### NP21. Compare NumPy vs Pandas performance on a large array.
import time
print("===========checking numpy time=========")
arr=np.arange(1000000)

start=time.time()
print(arr*2+1)
end=time.time()

result=end-start
print("numpy array time :",result)
print()
print("============check series time =============")
arr1=pd.Series(arr)

start=time.time()
print(arr1*2+1)
end=time.time()

result_pd=end-start
print("pandas series time :" ,result_pd)

===========checking numpy time=========
[      1       3       5 ... 1999995 1999997 1999999]
numpy array time : 0.023537397384643555

============check series time =============
0               1
1               3
2               5
3               7
4               9
           ...
999995    1999991
999996    1999993
999997    1999995
999998    1999997
999999    1999999
Length: 1000000, dtype: int64
pandas series time : 0.0365753173828125

In [25]:
### NP22. Calculate cumulative sum using NumPy.
print(np.cumsum(df['Marks'].values))
print()
df['stud_marks']=np.cumsum(df['Marks'])
print(df['stud_marks'])

[ 85. 175.  nan  nan]

0     85.0
1    175.0
2      NaN
3    263.0
Name: stud_marks, dtype: float64

In [26]:
### NP23. Use `np.argmax` and `np.argmin`.
idx=np.argmax(student['marks'].values)
print(idx)
print(student.iloc[idx])
print(student.loc[idx])

6
present     17
absent      10
rollno     107
marks       96
Name: 6, dtype: int64
present     17
absent      10
rollno     107
marks       96
Name: 6, dtype: int64

In [27]:
### NP24. Sort values using NumPy `np.argsort`.
sorted_idx=np.argsort(student['marks'].values)
print(sorted_idx)
print(student.iloc[sorted_idx])
print("==============on present column==========")

[18 44 16 15 20 11 33 12 30 45  9 31 27 37 19 38 34 39 48 29  2 49 23  4
 24 41 36 28 43 10 42  1 22 47  0  8 40  5 21 17 25 13 26 46  7 35  3 14
 32  6]
    present  absent  rollno  marks
18       16      10     119     35
44       17       5     145     35
16       22       6     117     36
15       24       4     116     36
20       10       6     121     36
11       24       6     112     36
33       18       8     134     37
12       30       0     113     37
30       14      10     131     45
45       12       7     146     45
9        22       9     110     46
31       19       9     132     50
27       12       4     128     51
37       21       8     138     53
19       18       3     120     53
38       11      10     139     53
34       16       6     135     54
39       10       8     140     54
48       14       4     149     57
29       10       3     130     58
2        25       4     103     58
49       24       0     150     65
23       20       5     124     66
4        17       6     105     66
24       28       1     125     66
41       14       8     142     67
36       17       0     137     70
28       12       5     129     72
43       21       6     144     73
10       27       2     111     73
42       12       2     143     74
1        23       0     102     78
22       17       2     123     78
47       12       8     148     84
0        13       2     101     85
8        25       9     109     86
40       25       3     141     86
5        23       6     106     86
21       21      10     122     87
17       10       6     118     88
25       26       9     126     89
13       22       3     114     90
26       17       8     127     90
46       10      10     147     91
7        30       8     108     92
35       18       0     136     93
3        24       9     104     93
14       18       3     115     93
32       16       6     133     93
6        17      10     107     96
==============on present column==========

In [28]:
### NP25. Compute correlation using `np.corrcoef`.
print(np.corrcoef([student['absent'].values , 
                   student['present'].values]))

arr=np.array([[1,2],
              [3,4]])
print()

[[ 1.         -0.20499612]
 [-0.20499612  1.        ]]

In [29]:
### NP26. Detect NaN values using NumPy.
arr = np.array([10, 20, np.nan])
arr1=pd.Series(arr)

print(np.isnan(arr))
print(np.isnan(arr).sum())
print("====pd.isnull=========")
print(pd.isnull(arr1))

[False False  True]
1
====pd.isnull=========
0    False
1    False
2     True
dtype: bool

In [30]:
### NP27. Create boolean masks using NumPy.
#print(student)
mask=(np.array(student['marks'])>80 & (np.array(student['absent'])<10))
print(mask)
print(student[mask])

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]
    present  absent  rollno  marks
0        13       2     101     85
1        23       0     102     78
2        25       4     103     58
3        24       9     104     93
4        17       6     105     66
5        23       6     106     86
6        17      10     107     96
7        30       8     108     92
8        25       9     109     86
9        22       9     110     46
10       27       2     111     73
11       24       6     112     36
12       30       0     113     37
13       22       3     114     90
14       18       3     115     93
15       24       4     116     36
16       22       6     117     36
17       10       6     118     88
18       16      10     119     35
19       18       3     120     53
20       10       6     121     36
21       21      10     122     87
22       17       2     123     78
23       20       5     124     66
24       28       1     125     66
25       26       9     126     89
26       17       8     127     90
27       12       4     128     51
28       12       5     129     72
29       10       3     130     58
30       14      10     131     45
31       19       9     132     50
32       16       6     133     93
33       18       8     134     37
34       16       6     135     54
35       18       0     136     93
36       17       0     137     70
37       21       8     138     53
38       11      10     139     53
39       10       8     140     54
40       25       3     141     86
41       14       8     142     67
42       12       2     143     74
43       21       6     144     73
44       17       5     145     35
45       12       7     146     45
46       10      10     147     91
47       12       8     148     84
48       14       4     149     57
49       24       0     150     65

In [31]:
### NP28. Apply logical operations (`np.logical_and`, `np.logical_or`, `np.logical_not`)
cond1=student['present'].values >12
cond2=student['absent'].values  > 4
logi_and=np.logical_and(cond1, cond2)
print(student[logi_and])
print(np.logical_and(cond1, cond2))

logi_or=np.logical_or(cond1,cond1)
print(student[logi_or])
print(np.logical_or(cond1,cond1))

print(np.logical_not(cond1,cond2))
logical_not=np.logical_not(cond1,cond2)
print(student[logical_not])

    present  absent  rollno  marks
3        24       9     104     93
4        17       6     105     66
5        23       6     106     86
6        17      10     107     96
7        30       8     108     92
8        25       9     109     86
9        22       9     110     46
11       24       6     112     36
16       22       6     117     36
18       16      10     119     35
21       21      10     122     87
23       20       5     124     66
25       26       9     126     89
26       17       8     127     90
30       14      10     131     45
31       19       9     132     50
32       16       6     133     93
33       18       8     134     37
34       16       6     135     54
37       21       8     138     53
41       14       8     142     67
43       21       6     144     73
44       17       5     145     35
[False False False  True  True  True  True  True  True  True False  True
 False False False False  True False  True False False  True False  True
 False  True  True False False False  True  True  True  True  True False
 False  True False False False  True False  True  True False False False
 False False]
    present  absent  rollno  marks
0        13       2     101     85
1        23       0     102     78
2        25       4     103     58
3        24       9     104     93
4        17       6     105     66
5        23       6     106     86
6        17      10     107     96
7        30       8     108     92
8        25       9     109     86
9        22       9     110     46
10       27       2     111     73
11       24       6     112     36
12       30       0     113     37
13       22       3     114     90
14       18       3     115     93
15       24       4     116     36
16       22       6     117     36
18       16      10     119     35
19       18       3     120     53
21       21      10     122     87
22       17       2     123     78
23       20       5     124     66
24       28       1     125     66
25       26       9     126     89
26       17       8     127     90
30       14      10     131     45
31       19       9     132     50
32       16       6     133     93
33       18       8     134     37
34       16       6     135     54
35       18       0     136     93
36       17       0     137     70
37       21       8     138     53
40       25       3     141     86
41       14       8     142     67
43       21       6     144     73
44       17       5     145     35
48       14       4     149     57
49       24       0     150     65
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True False  True  True False  True  True  True
  True  True  True False False False  True  True  True  True  True  True
  True  True False False  True  True False  True  True False False False
  True  True]
[False False False False False False False False False False False False
 False False False False False  True False False  True False False False
 False False False  True  True  True False False False False False False
 False False  True  True False False  True False False  True  True  True
 False False]
    present  absent  rollno  marks
17       10       6     118     88
20       10       6     121     36
27       12       4     128     51
28       12       5     129     72
29       10       3     130     58
38       11      10     139     53
39       10       8     140     54
42       12       2     143     74
45       12       7     146     45
46       10      10     147     91
47       12       8     148     84

In [32]:
### NP29. Apply `np.select` for multi-condition assignment.
student['Grades']=np.select([student['marks']>= 90 , student['marks'] >= 75], ['A','B'], default='C')
print(student['Grades'])

0     B
1     B
2     C
3     A
4     C
5     B
6     A
7     A
8     B
9     C
10    C
11    C
12    C
13    A
14    A
15    C
16    C
17    B
18    C
19    C
20    C
21    B
22    B
23    C
24    C
25    B
26    A
27    C
28    C
29    C
30    C
31    C
32    A
33    C
34    C
35    A
36    C
37    C
38    C
39    C
40    B
41    C
42    C
43    C
44    C
45    C
46    A
47    B
48    C
49    C
Name: Grades, dtype: str

In [33]:
### NP30. Multiply DataFrame columns element-wise using NumPy.
print(np.multiply(student['present'].values, student['absent'].values))
print(student['present']* student['absent'])

[ 26   0 100 216 102 138 170 240 225 198  54 144   0  66  54  96 132  60
 160  54  60 210  34 100  28 234 136  48  60  30 140 171  96 144  96   0
   0 168 110  80  75 112  24 126  85  84 100  96  56   0]
0      26
1       0
2     100
3     216
4     102
5     138
6     170
7     240
8     225
9     198
10     54
11    144
12      0
13     66
14     54
15     96
16    132
17     60
18    160
19     54
20     60
21    210
22     34
23    100
24     28
25    234
26    136
27     48
28     60
29     30
30    140
31    171
32     96
33    144
34     96
35      0
36      0
37    168
38    110
39     80
40     75
41    112
42     24
43    126
44     85
45     84
46    100
47     96
48     56
49      0
dtype: int32

## 🔹 NP31–NP40: Data Wrangling & Conversion

In [34]:
### NP31. Shuffle dataset rows using NumPy.
#Shuffling means randomly rearranging the rows of a dataset.
shuffled_idx=np.random.permutation(student.index)
print(shuffled_idx)

print()
print(student.loc[shuffled_idx].reset_index(drop=True))

[33  0 34 12 10 15 30  4 49 37 32 22 23 26 18 44 31 21  9  5 35 39 29 41
 40 16 42 47 14  7 28 11 45 27 19  1 25 48 13 24  3 17 38  8 20  6 36  2
 43 46]

    present  absent  rollno  marks Grades
0        18       8     134     37      C
1        13       2     101     85      B
2        16       6     135     54      C
3        30       0     113     37      C
4        27       2     111     73      C
5        24       4     116     36      C
6        14      10     131     45      C
7        17       6     105     66      C
8        24       0     150     65      C
9        21       8     138     53      C
10       16       6     133     93      A
11       17       2     123     78      B
12       20       5     124     66      C
13       17       8     127     90      A
14       16      10     119     35      C
15       17       5     145     35      C
16       19       9     132     50      C
17       21      10     122     87      B
18       22       9     110     46      C
19       23       6     106     86      B
20       18       0     136     93      A
21       10       8     140     54      C
22       10       3     130     58      C
23       14       8     142     67      C
24       25       3     141     86      B
25       22       6     117     36      C
26       12       2     143     74      C
27       12       8     148     84      B
28       18       3     115     93      A
29       30       8     108     92      A
30       12       5     129     72      C
31       24       6     112     36      C
32       12       7     146     45      C
33       12       4     128     51      C
34       18       3     120     53      C
35       23       0     102     78      B
36       26       9     126     89      B
37       14       4     149     57      C
38       22       3     114     90      A
39       28       1     125     66      C
40       24       9     104     93      A
41       10       6     118     88      B
42       11      10     139     53      C
43       25       9     109     86      B
44       10       6     121     36      C
45       17      10     107     96      A
46       17       0     137     70      C
47       25       4     103     58      C
48       21       6     144     73      C
49       10      10     147     91      A

NumPy	                                                    Pandas

np.random.choice()        	                             df.sample()

First select indices	                               Directly returns rows

More control over random                               selection	Easier to use

Useful in NumPy workflows	                             Common in Pandas workflows

In [35]:
### NP32. Sample random rows using NumPy.
sample_idx=np.random.choice(student.index, size=10 , replace=False)
print(sample_idx)
print(student.loc[sample_idx])

[26  3 35 29 31 20 22 46 12 17]
    present  absent  rollno  marks Grades
26       17       8     127     90      A
3        24       9     104     93      A
35       18       0     136     93      A
29       10       3     130     58      C
31       19       9     132     50      C
20       10       6     121     36      C
22       17       2     123     78      B
46       10      10     147     91      A
12       30       0     113     37      C
17       10       6     118     88      B

In [36]:
### NP33. Calculate percentiles using NumPy.
print(np.percentile(student['marks'].values , [25,50,75]))
p=[0,100]
print(np.percentile(student['marks'], p))

[51.5 66.5 86. ]
[35. 96.]

In [37]:
### NP34. Calculate variance and standard deviation.
#ddof = Delta Degrees of Freedom
print(np.var(student['marks'],ddof=0))
print(np.std(student['marks'],ddof=0))

401.17
20.029228642161936

In [38]:
### NP35. Replace a DataFrame column with a NumPy array.
new_numpy_array=np.array([22,21,25,19])
df['age']=new_numpy_array
print(df)

    Name   Age  Marks  stud_marks  age
0  Alice  20.0   85.0        85.0   22
1    Bob   NaN   90.0       175.0   21
2    NaN  22.0    NaN         NaN   25
3  David  23.0   88.0       263.0   19

In [39]:
### NP36. Convert DataFrame to NumPy using `to_numpy()`.
new_arr=df[['age','Marks']].to_numpy
print(new_arr)

<bound method DataFrame.to_numpy of    age  Marks
0   22   85.0
1   21   90.0
2   25    NaN
3   19   88.0>

In [40]:
### NP37. Compare `.values` vs `.to_numpy()`.
value=df['age'].values
print(value)
to_num=df['age'].to_numpy(dtype=np.float32)
print(to_num)

equal=np.array_equal(value , to_num)
print(equal)

[22 21 25 19]
[22. 21. 25. 19.]
True

In [41]:
### NP38. Slice a column using NumPy array indexing.
print(df['Age'][::2].values)
print(df['Age'][::-1].values)
print(df['age'][[0,2,3]].values)

[20. 22.]
[23. 22. nan 20.]
[22 25 19]

In [42]:
### NP39. Merge NumPy-generated data into a DataFrame.
#first arr
arr1 = np.array([
    [1, "Rahul", 85],
    [2, "Priya", 90],
    [3, "Amit", 78],
    [4, "Neha", 92]
])
df5 = pd.DataFrame(arr1, columns=["ID", "Name", "Marks"])
#seccond arr
arr2 = np.array([
    [1, "Pune"],
    [2, "Mumbai"],
    [3, "Delhi"],
    [4, "Bangalore"]
])
df6 = pd.DataFrame(arr2, columns=["ID", "City"])
merge=pd.merge(df5, df6 , on='ID',how='outer')
#Keep ALL rows from BOTH DataFrames.
#Even if an ID exists in only one DataFrame, it will still appear in the result.
print(merge)

  ID   Name Marks       City
0  1  Rahul    85       Pune
1  2  Priya    90     Mumbai
2  3   Amit    78      Delhi
3  4   Neha    92  Bangalore

Q: Why use rolling computations?

A: They help analyze trends over time by smoothing short-term fluctuations.

Examples:

Stock market moving averages
Daily temperature averages
Weekly sales trends
Sensor data smoothing

A rolling window looks at a small chunk of recent values and computes a statistic such as mean, sum, min, max, or standard deviation.

In [43]:
### NP40. Apply rolling computation using NumPy.
w=4
print([np.mean(arr[max(0,i-w+1):i+1]) for i in range(len(arr))])
print(df5['ID'].rolling(w).mean())

[np.float64(10.0), np.float64(15.0), np.float64(nan)]
0    NaN
1    NaN
2    NaN
3    2.5
Name: ID, dtype: float64

## 🔹 NP41–NP50: ML-Ready Dataset Preparation

In [44]:
### NP41. Create a synthetic ML dataset using NumPy.
synthetic=pd.DataFrame({
    'marks':np.random.randint(40,99,100), #Generates random integers.
    'study_hours':np.random.normal(5,2,100), #Generates values from a normal distribution.
    'gender' :np.random.choice(
        ['female',' male']
    ) #Randomly selects categories
})

synthetic['result']=np.where(
    synthetic['study_hours']>=5,
    'pass',
    'fail'
) #Create a binary label.
print(synthetic['result'])

condition=[
    synthetic['study_hours']>=5,
    synthetic['study_hours']>=3,
    synthetic['study_hours']>=1
]

choice=[
    'excellent',
    'good',
    'average'
]

synthetic['performance']=np.select(
    condition,
    choice,
    default='Poor'
)
print(synthetic['performance'])

0     pass
1     fail
2     fail
3     pass
4     fail
      ...
95    pass
96    fail
97    fail
98    pass
99    fail
Name: result, Length: 100, dtype: str
0     excellent
1       average
2          good
3     excellent
4       average
        ...
95    excellent
96         good
97      average
98    excellent
99      average
Name: performance, Length: 100, dtype: str

In [45]:
### NP42. Detect and replace outliers using NumPy.
Q1=np.percentile(synthetic['marks'],25)
print('Q1 :', Q1)
Q3=np.percentile(synthetic['marks'], 75)
print('Q3 :', Q3)
IQR=Q3-Q1
print("IQR : ",IQR)
lower_outliers=(Q1-1.5*IQR)
upper_outliers=(Q3+1.5*IQR)

outliers=[
    (synthetic['marks']<lower_outliers),
    (synthetic['marks'] > upper_outliers)
]
print("======outliers=====")
print(outliers)

replace_outliers=np.clip(synthetic['marks'], lower_outliers,upper_outliers)
print(replace_outliers)

Q1 : 60.5
Q3 : 88.0
IQR :  27.5
======outliers=====
[0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: marks, Length: 100, dtype: bool, 0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: marks, Length: 100, dtype: bool]
0     65
1     81
2     52
3     90
4     71
      ..
95    40
96    58
97    41
98    92
99    83
Name: marks, Length: 100, dtype: int32

In [46]:
### NP43. Scale dataset using NumPy functions.
min_z=np.min(synthetic['marks'].values)
print(min_z)
max_z=np.max(synthetic['marks'].values)
print(max_z)
synthetic['minmax_scaled']=(synthetic['marks']-min_z)/(max_z-min_z)
print(synthetic['minmax_scaled'])

z_mean=np.mean(synthetic['marks'].values)
print(z_mean)
z_std=np.std(synthetic['marks'].values)
print(z_std)

synthetic['zscore_scaled']=(synthetic['marks']-z_mean)/z_std
print(synthetic['zscore_scaled'])

print(synthetic)

40
98
0     0.431034
1     0.706897
2     0.206897
3     0.862069
4     0.534483
        ...
95    0.000000
96    0.310345
97    0.017241
98    0.896552
99    0.741379
Name: minmax_scaled, Length: 100, dtype: float64
71.87
17.379099516373106
0    -0.395302
1     0.525344
2    -1.143327
3     1.043207
4    -0.050060
        ...
95   -1.833812
96   -0.798085
97   -1.776272
98    1.158288
99    0.640424
Name: zscore_scaled, Length: 100, dtype: float64
    marks  study_hours gender result performance  minmax_scaled  zscore_scaled
0      65     8.930070   male   pass   excellent       0.431034      -0.395302
1      81     1.120178   male   fail     average       0.706897       0.525344
2      52     3.474746   male   fail        good       0.206897      -1.143327
3      90     5.337319   male   pass   excellent       0.862069       1.043207
4      71     2.356246   male   fail     average       0.534483      -0.050060
..    ...          ...    ...    ...         ...            ...            ...
95     40     8.557849   male   pass   excellent       0.000000      -1.833812
96     58     3.666113   male   fail        good       0.310345      -0.798085
97     41     1.616363   male   fail     average       0.017241      -1.776272
98     92     6.313595   male   pass   excellent       0.896552       1.158288
99     83     2.128198   male   fail     average       0.741379       0.640424

[100 rows x 7 columns]

In [47]:

### NP44. Engineer new features using NumPy.
square1=np.square(synthetic['marks'])
print(square1)
power1=np.power(synthetic['marks'],2)
print(power1)

# 3 log
logg=np.log1p(synthetic['marks'])
print(logg)

#interaction 2 columns
synthetic['marks_study']=(
    synthetic['marks'] *synthetic['study_hours']
)
print(synthetic['marks_study'])

# bins digitizing
bins=[50,60] #Convert continuous values into categories.
synthetic['marks_bin']=np.digitize(synthetic['marks'],bins)
print(synthetic['marks_bin'])

0     4225
1     6561
2     2704
3     8100
4     5041
      ...
95    1600
96    3364
97    1681
98    8464
99    6889
Name: marks, Length: 100, dtype: int32
0     4225
1     6561
2     2704
3     8100
4     5041
      ...
95    1600
96    3364
97    1681
98    8464
99    6889
Name: marks, Length: 100, dtype: int32
0     4.189655
1     4.406719
2     3.970292
3     4.510860
4     4.276666
        ...
95    3.713572
96    4.077537
97    3.737670
98    4.532599
99    4.430817
Name: marks, Length: 100, dtype: float64
0     580.454519
1      90.734383
2     180.686796
3     480.358690
4     167.293473
         ...
95    342.313948
96    212.634569
97     66.270903
98    580.850709
99    176.640464
Name: marks_study, Length: 100, dtype: float64
0     2
1     2
2     1
3     2
4     2
     ..
95    0
96    1
97    0
98    2
99    2
Name: marks_bin, Length: 100, dtype: int64

In [48]:
### NP45. Use exponential functions (`np.exp`).
exponential=np.exp(synthetic['marks'].values)
print(exponential)

logg=np.log(synthetic['marks'].values)
print(logg)
#It is the inverse operation of logarithm.

[1.69488924e+28 1.50609731e+35 3.83100800e+22 1.22040329e+39
 6.83767123e+30 7.49841700e+33 1.65163625e+38 3.31740010e+39
 6.83767123e+30 4.72783947e+18 9.25378173e+29 1.01480039e+33
 8.43835667e+26 7.49841700e+33 3.02507732e+36 2.83075330e+23
 4.09399696e+35 3.40427605e+29 3.73324200e+32 3.83100800e+22
 6.83767123e+30 9.49611942e+19 3.63797095e+42 1.22040329e+39
 3.10429794e+26 1.25236317e+29 6.39843494e+17 1.50609731e+35
 3.02507732e+36 4.92345829e+41 9.01762841e+39 3.49342711e+19
 1.25236317e+29 1.25236317e+29 1.11286375e+36 1.11286375e+36
 4.20121040e+25 9.25378173e+29 5.18470553e+21 1.33833472e+42
 6.66317622e+40 1.25236317e+29 6.23514908e+27 7.49841700e+33
 1.85867175e+31 2.35385267e+17 4.92345829e+41 4.60718663e+28
 4.92345829e+41 3.31740010e+39 3.83100800e+22 5.54062238e+34
 1.73927494e+18 7.49841700e+33 3.49342711e+19 2.58131289e+20
 4.60718663e+28 7.01673591e+20 1.01480039e+33 1.85867175e+31
 1.22040329e+39 1.50609731e+35 1.11286375e+36 2.29378316e+27
 2.83075330e+23 3.63797095e+42 2.45124554e+40 6.83767123e+30
 6.83767123e+30 2.29378316e+27 5.54062238e+34 3.31740010e+39
 1.65163625e+38 1.65163625e+38 1.33833472e+42 3.31740010e+39
 1.40934908e+22 7.49841700e+33 6.39843494e+17 1.73927494e+18
 1.65163625e+38 1.01480039e+33 1.65163625e+38 1.81123908e+41
 2.09165950e+24 3.63797095e+42 1.65163625e+38 6.39843494e+17
 6.39843494e+17 1.25236317e+29 2.45124554e+40 8.43835667e+26
 1.01480039e+33 6.83767123e+30 1.85867175e+31 2.35385267e+17
 1.54553894e+25 6.39843494e+17 9.01762841e+39 1.11286375e+36]
[4.17438727 4.39444915 3.95124372 4.49980967 4.26267988 4.35670883
 4.47733681 4.51085951 4.26267988 3.76120012 4.2341065  4.33073334
 4.12713439 4.35670883 4.4308168  3.98898405 4.40671925 4.21950771
 4.31748811 3.95124372 4.26267988 3.8286414  4.58496748 4.49980967
 4.11087386 4.20469262 3.71357207 4.39444915 4.4308168  4.56434819
 4.52178858 3.80666249 4.20469262 4.20469262 4.41884061 4.41884061
 4.07753744 4.2341065  3.91202301 4.57471098 4.54329478 4.20469262
 4.15888308 4.35670883 4.27666612 3.68887945 4.56434819 4.18965474
 4.56434819 4.51085951 3.95124372 4.38202663 3.73766962 4.35670883
 3.80666249 3.8501476  4.18965474 3.87120101 4.33073334 4.27666612
 4.49980967 4.39444915 4.41884061 4.14313473 3.98898405 4.58496748
 4.53259949 4.26267988 4.26267988 4.14313473 4.38202663 4.51085951
 4.47733681 4.47733681 4.57471098 4.51085951 3.93182563 4.35670883
 3.71357207 3.73766962 4.47733681 4.33073334 4.47733681 4.55387689
 4.02535169 4.58496748 4.47733681 3.71357207 3.71357207 4.20469262
 4.53259949 4.12713439 4.33073334 4.26267988 4.27666612 3.68887945
 4.06044301 3.71357207 4.52178858 4.41884061]

In [49]:
### NP46. Compute differences using `np.diff`.
diff=np.diff(synthetic['marks'].values)
print(diff)
#np.diff() calculates the difference between consecutive elements.
#values converts a Pandas Series or DataFrame into a NumPy array
#Since the DataFrame has n rows, we need one extra value at the beginning.
synthetic['col_diff']=np.insert(np.diff(synthetic['study_hours']), 0 , np.nan)
print(synthetic['col_diff'])

[ 16 -29  38 -19   7  10   3 -20 -28  26   7 -14  16   6 -30  28 -14   7
 -23  19 -25  52  -8 -29   6 -26  40   3  12  -4 -47  22   0  16   0 -24
  10 -19  47  -3 -27  -3  14  -6 -32  56 -30  30  -5 -39  28 -38  36 -33
   2  19 -18  28  -4  18  -9   2 -20  -9  44  -5 -22   0  -8  17  11  -3
   0   9  -6 -40  27 -37   1  46 -12  12   7 -39  42 -10 -47   0  26  26
 -31  14  -5   1 -32  18 -17  51  -9]
0          NaN
1    -7.809892
2     2.354569
3     1.862573
4    -2.981073
        ...
95    2.658301
96   -4.891735
97   -2.049750
98    4.697231
99   -4.185396
Name: col_diff, Length: 100, dtype: float64

In [50]:
### NP47. Apply conditional encoding using NumPy.
condition=[
    synthetic['marks']>=90,
    synthetic['marks']>=75,
    synthetic['marks']>=60
]

choice=[
    'destination',
    'first class',
    'second class'
]
synthetic['greads']=np.select(
    condition,
    choice,
    default='third class'
)
print(synthetic['greads'])

0     second class
1      first class
2      third class
3      destination
4     second class
          ...
95     third class
96     third class
97     third class
98     destination
99     first class
Name: greads, Length: 100, dtype: str

In [51]:
### NP48. Build an ML-ready dataset (feature matrix X and label vector y).
print(student)
x=student[['present','absent','rollno' , 'marks']].to_numpy(dtype=np.float32)
print(x)
print(x.shape)

y=(student['marks'] >= 78).astype(int).to_numpy()
print(y)
print(y.shape)

    present  absent  rollno  marks Grades
0        13       2     101     85      B
1        23       0     102     78      B
2        25       4     103     58      C
3        24       9     104     93      A
4        17       6     105     66      C
5        23       6     106     86      B
6        17      10     107     96      A
7        30       8     108     92      A
8        25       9     109     86      B
9        22       9     110     46      C
10       27       2     111     73      C
11       24       6     112     36      C
12       30       0     113     37      C
13       22       3     114     90      A
14       18       3     115     93      A
15       24       4     116     36      C
16       22       6     117     36      C
17       10       6     118     88      B
18       16      10     119     35      C
19       18       3     120     53      C
20       10       6     121     36      C
21       21      10     122     87      B
22       17       2     123     78      B
23       20       5     124     66      C
24       28       1     125     66      C
25       26       9     126     89      B
26       17       8     127     90      A
27       12       4     128     51      C
28       12       5     129     72      C
29       10       3     130     58      C
30       14      10     131     45      C
31       19       9     132     50      C
32       16       6     133     93      A
33       18       8     134     37      C
34       16       6     135     54      C
35       18       0     136     93      A
36       17       0     137     70      C
37       21       8     138     53      C
38       11      10     139     53      C
39       10       8     140     54      C
40       25       3     141     86      B
41       14       8     142     67      C
42       12       2     143     74      C
43       21       6     144     73      C
44       17       5     145     35      C
45       12       7     146     45      C
46       10      10     147     91      A
47       12       8     148     84      B
48       14       4     149     57      C
49       24       0     150     65      C
[[ 13.   2. 101.  85.]
 [ 23.   0. 102.  78.]
 [ 25.   4. 103.  58.]
 [ 24.   9. 104.  93.]
 [ 17.   6. 105.  66.]
 [ 23.   6. 106.  86.]
 [ 17.  10. 107.  96.]
 [ 30.   8. 108.  92.]
 [ 25.   9. 109.  86.]
 [ 22.   9. 110.  46.]
 [ 27.   2. 111.  73.]
 [ 24.   6. 112.  36.]
 [ 30.   0. 113.  37.]
 [ 22.   3. 114.  90.]
 [ 18.   3. 115.  93.]
 [ 24.   4. 116.  36.]
 [ 22.   6. 117.  36.]
 [ 10.   6. 118.  88.]
 [ 16.  10. 119.  35.]
 [ 18.   3. 120.  53.]
 [ 10.   6. 121.  36.]
 [ 21.  10. 122.  87.]
 [ 17.   2. 123.  78.]
 [ 20.   5. 124.  66.]
 [ 28.   1. 125.  66.]
 [ 26.   9. 126.  89.]
 [ 17.   8. 127.  90.]
 [ 12.   4. 128.  51.]
 [ 12.   5. 129.  72.]
 [ 10.   3. 130.  58.]
 [ 14.  10. 131.  45.]
 [ 19.   9. 132.  50.]
 [ 16.   6. 133.  93.]
 [ 18.   8. 134.  37.]
 [ 16.   6. 135.  54.]
 [ 18.   0. 136.  93.]
 [ 17.   0. 137.  70.]
 [ 21.   8. 138.  53.]
 [ 11.  10. 139.  53.]
 [ 10.   8. 140.  54.]
 [ 25.   3. 141.  86.]
 [ 14.   8. 142.  67.]
 [ 12.   2. 143.  74.]
 [ 21.   6. 144.  73.]
 [ 17.   5. 145.  35.]
 [ 12.   7. 146.  45.]
 [ 10.  10. 147.  91.]
 [ 12.   8. 148.  84.]
 [ 14.   4. 149.  57.]
 [ 24.   0. 150.  65.]]
(50, 4)
[1 1 0 1 0 1 1 1 1 0 0 0 0 1 1 0 0 1 0 0 0 1 1 0 0 1 1 0 0 0 0 0 1 0 0 1 0
 0 0 0 1 0 0 0 0 0 1 1 0 0]
(50,)

In [52]:
### NP49. Perform a mini data analysis project.
np.random.seed(42)
n=100
student=pd.DataFrame({
    'student_id' : np.arange(1,n+1),
    'subjects' : np.random.choice(['python','java','c++','c']),
    'python':  np.random.randint(40 , 101 ,n).astype(float),
    'java':    np.random.randint(40 , 101 ,n).astype(float),
    'c++':     np.random.randint(40 , 101 ,n).astype(float),
    'c':       np.random.randint(40 , 101 ,n).astype(float),
})
print(student)
student.loc[67, 'python'] = np.nan
student.loc[50, 'java'] = np.nan
student.loc[78, 'c++'] = np.nan

#inspect data
print("===============inspected data============")
print(student.head())
print(student.info())
print(student.describe())
print(student.dtypes)
#df=student.drop_duplicates()
print(student.isnull().sum())

#cleaning data
print("=================cleaned data===============")
student['python']=student['python'].fillna(student['python'].mean())
student['java']=student['java'].fillna(student['java'].mean())
student['c++']=student['c++'].fillna(student['c++'].mean())
student['c']=student['c'].fillna(student['c'].mean())

print(student.isnull().sum())

print("=========== feature Engineering========")
subject_col=['python','java','c++','c']

student['Total']=student[subject_col].sum(axis=1)

student['percentage']=(student['Total']/400)*100

student['percentage']=student['percentage'].round(2)
print(student.tail())

print(student.describe)

print("=============group by===========")
group_data=student.groupby('subjects').agg({
    'python':['max','min','sum'],
    'java':['max','min','sum'],
    'c++': ['max','min','sum'],
    'c' : ['max','min','sum']
})
print(group_data)

print("==============pivot table=========")
pivot_data=pd.pivot_table(student,
                     values='Total',
                     index='subjects',
                     aggfunc='mean'     
)
print(pivot_data)

print("=============outliers========")
Q1=student['percentage'].quantile(0.25)
Q3=student['percentage'].quantile(0.75)
print("Q1 : ",Q1)
print("Q2 : ",Q3)

IQR=Q3-Q1
print("IQR : ",IQR)

lower=Q1-1.5*IQR
upper=Q3+1.5*IQR

outliers=student[
    (student['percentage']<lower)|
    (student['percentage']>upper)
]
print(outliers)
Export_csv=student.describe()
print("======== export data========")
Export_csv.to_csv("student_analysis.csv")

    student_id subjects  python  java   c++     c
0            1      c++    91.0  54.0  75.0  50.0
1            2      c++    68.0  47.0  52.0  87.0
2            3      c++    54.0  53.0  71.0  55.0
3            4      c++    82.0  62.0  46.0  72.0
4            5      c++    47.0  99.0  98.0  48.0
..         ...      ...     ...   ...   ...   ...
95          96      c++    49.0  78.0  44.0  72.0
96          97      c++    75.0  84.0  91.0  43.0
97          98      c++    53.0  54.0  73.0  72.0
98          99      c++    70.0  82.0  45.0  53.0
99         100      c++    87.0  68.0  61.0  60.0

[100 rows x 6 columns]
===============inspected data============
   student_id subjects  python  java   c++     c
0           1      c++    91.0  54.0  75.0  50.0
1           2      c++    68.0  47.0  52.0  87.0
2           3      c++    54.0  53.0  71.0  55.0
3           4      c++    82.0  62.0  46.0  72.0
4           5      c++    47.0  99.0  98.0  48.0
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  100 non-null    int64
 1   subjects    100 non-null    str
 2   python      99 non-null     float64
 3   java        99 non-null     float64
 4   c++         99 non-null     float64
 5   c           100 non-null    float64
dtypes: float64(4), int64(1), str(1)
memory usage: 4.8 KB
None

       student_id      python        java        c++           c
count  100.000000   99.000000   99.000000  99.000000  100.000000
mean    50.500000   71.090909   69.282828  71.333333   69.780000
std     29.011492   18.377610   17.199336  18.490483   17.570395
min      1.000000   41.000000   40.000000  40.000000   40.000000
25%     25.750000   55.500000   54.000000  56.000000   56.500000
50%     50.500000   70.000000   69.000000  72.000000   71.000000
75%     75.250000   87.500000   82.500000  88.000000   85.500000
max    100.000000  100.000000  100.000000  98.000000  100.000000
student_id      int64
subjects          str
python        float64
java          float64
c++           float64
c             float64
dtype: object
student_id    0
subjects      0
python        1
java          1
c++           1
c             0
dtype: int64
=================cleaned data===============
student_id    0
subjects      0
python        0
java          0
c++           0
c             0
dtype: int64
=========== feature Engineering========
    student_id subjects  python  java   c++     c  Total  percentage
95          96      c++    49.0  78.0  44.0  72.0  243.0       60.75
96          97      c++    75.0  84.0  91.0  43.0  293.0       73.25
97          98      c++    53.0  54.0  73.0  72.0  252.0       63.00
98          99      c++    70.0  82.0  45.0  53.0  250.0       62.50
99         100      c++    87.0  68.0  61.0  60.0  276.0       69.00
<bound method NDFrame.describe of     student_id subjects  python  java   c++     c  Total  percentage
0            1      c++    91.0  54.0  75.0  50.0  270.0       67.50
1            2      c++    68.0  47.0  52.0  87.0  254.0       63.50
2            3      c++    54.0  53.0  71.0  55.0  233.0       58.25
3            4      c++    82.0  62.0  46.0  72.0  262.0       65.50
4            5      c++    47.0  99.0  98.0  48.0  292.0       73.00
..         ...      ...     ...   ...   ...   ...    ...         ...
95          96      c++    49.0  78.0  44.0  72.0  243.0       60.75
96          97      c++    75.0  84.0  91.0  43.0  293.0       73.25
97          98      c++    53.0  54.0  73.0  72.0  252.0       63.00
98          99      c++    70.0  82.0  45.0  53.0  250.0       62.50
99         100      c++    87.0  68.0  61.0  60.0  276.0       69.00

[100 rows x 8 columns]>
=============group by===========
         python                      java                      c++        \
            max   min          sum    max   min          sum   max   min
subjects
c++       100.0  41.0  7109.090909  100.0  40.0  6928.282828  98.0  40.0

                           c
                  sum    max   min     sum
subjects
c++       7133.333333  100.0  40.0  6978.0
==============pivot table=========
               Total
subjects
c++       281.487071
=============outliers========
Q1 :  63.1875
Q2 :  75.625
IQR :  12.4375
   student_id subjects  python  java   c++     c  Total  percentage
5           6      c++   100.0  96.0  90.0  99.0  385.0       96.25
======== export data========

In [53]:
### NP50. Build an end-to-end pipeline using NumPy + Pandas.
print("==== create data==========")
np.random.seed(42)

n=1000
models = ['Toyota Corolla', 'Mazda CX-5', 'Ford Ranger', 'Hyundai i30', 'Tesla Model 3']
base_prices = {
    'Toyota Corolla': 32000,
    'Mazda CX-5': 45000,
    'Ford Ranger': 62000,
    'Hyundai i30': 29000,
    'Tesla Model 3': 68000
}
car_model=pd.DataFrame({
    'model_id' : np.arange(1, n+1),
    'Model_name' : np.random.choice(
        ['Swift', 'Creta', 'Baleno', 'Nexon', 'City'],
        n
    ),
    'model_price': np.random.randint(500000 , 2000000,n),
    'avg_per_hours': np.random.randint(20,120 ,n)
})
print(car_model.head())

print("===== clean in valid values ===========")
#np.clip() is used to limit values within a specified range.
cleaned = car_model.copy()
cleaned['model_price']=np.clip(cleaned['model_price'] ,500000,2000000)

cleaned['avg_per_hours'] = np.clip(
    cleaned['avg_per_hours'],
    20,
    120
)
print(cleaned.head())

print("=============feature Engineering========")
cleaned['log']=np.log(cleaned['model_price'].round(4))
print(cleaned['log'])
cleaned['square']=np.square(cleaned['model_price'].round(4))
print(cleaned['square'])

cleaned['price_category']=np.where(cleaned['model_price'] < 1000000,
                                   'Affordable',
                                   np.where(
        cleaned['model_price'] < 1500000,
        'Mid Range',
        'Expensive'
    )
                                   )
print(cleaned['price_category'].head())

print("============= group by ===========")
grouped_data=cleaned.groupby('Model_name').agg({
    'model_price':['min','max','mean'],
    'avg_per_hours':['min' , 'max' , 'mean']
})
print(group_data)

print("=============== outliers==========")
Q1=cleaned['model_price'].quantile(0.25)
Q3=cleaned['model_price'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-1.5*IQR
upper=Q3+1.5*IQR
outliers=cleaned[
    (cleaned['model_price']<lower)|
    (cleaned['model_price']>upper)
]
print(outliers)
print("total outliers : ",len(outliers))

#remove outliesrs
cleaned['model_price']=np.clip(
    cleaned['model_price'],
    lower, upper
)
print("============feature matrix========")
features = [
    'model_price',
    'avg_per_hours',
    'log',
    'square'
]
matrix=cleaned[features].to_numpy(dtype=np.float32)
print("shape : ",matrix.shape)


print("============export with=============")
export_csv=cleaned.to_csv("car_model.csv")
cleaned.to_excel("car_model_pipeline.xlsx", index=False)
print(" convert successfully !!!!!!!")

==== create data==========
   model_id Model_name  model_price  avg_per_hours
0         1      Nexon      1195275             62
1         2       City      1323651             40
2         3     Baleno      1760527             42
3         4       City       695716             99
4         5       City      1084567             66
===== clean in valid values ===========
   model_id Model_name  model_price  avg_per_hours
0         1      Nexon      1195275             62
1         2       City      1323651             40
2         3     Baleno      1760527             42
3         4       City       695716             99
4         5       City      1084567             66
=============feature Engineering========
0      13.993887
1      14.095904
2      14.381124
3      13.452697
4      13.896691
         ...
995    13.884203
996    14.449168
997    14.226665
998    13.732327
999    14.381595
Name: log, Length: 1000, dtype: float64
0     -1541783943
1      -294686967
2     -1511069983
3     -1310551792
4      -535461615
          ...
995     513937417
996    -635393692
997    -582410399
998     626355812
999    1412093737
Name: square, Length: 1000, dtype: int32
0     Mid Range
1     Mid Range
2     Expensive
3    Affordable
4     Mid Range
Name: price_category, dtype: str
============= group by ===========
         python                      java                      c++        \
            max   min          sum    max   min          sum   max   min
subjects
c++       100.0  41.0  7109.090909  100.0  40.0  6928.282828  98.0  40.0

                           c
                  sum    max   min     sum
subjects
c++       7133.333333  100.0  40.0  6978.0
=============== outliers==========
Empty DataFrame
Columns: [model_id, Model_name, model_price, avg_per_hours, log, square, price_category]
Index: []
total outliers :  0
============feature matrix========
shape :  (1000, 4)
============export with=============
 convert successfully !!!!!!!

In [54]:
#1. Create a DataFrame
df=pd.DataFrame({
    'Name': ['Dipali','Anu','Manas','anush','lila'],
    'Age' :[24,25,26,28,31],
    'City':['pune','kalaj','phalatan','baramati','satara']
})
print(df)
df['Salary']=[20000,10000,15000,16000,5000]
print(df)
#3. Display First Rows
print(df.head())

#4. Display Last Rows
print(df.tail(3))

#5. Check Shape
print(df.shape)


#6. View Column Names
print(df.columns)

#7. Check Data Types
print(df.dtypes)

#8. Select One Column
print(df['Name'])

#9. Select Multiple Columns
print(df[['Name','Age']])
print()

     Name  Age      City
0  Dipali   24      pune
1     Anu   25     kalaj
2   Manas   26  phalatan
3   anush   28  baramati
4    lila   31    satara
     Name  Age      City  Salary
0  Dipali   24      pune   20000
1     Anu   25     kalaj   10000
2   Manas   26  phalatan   15000
3   anush   28  baramati   16000
4    lila   31    satara    5000
     Name  Age      City  Salary
0  Dipali   24      pune   20000
1     Anu   25     kalaj   10000
2   Manas   26  phalatan   15000
3   anush   28  baramati   16000
4    lila   31    satara    5000
    Name  Age      City  Salary
2  Manas   26  phalatan   15000
3  anush   28  baramati   16000
4   lila   31    satara    5000
(5, 4)
Index(['Name', 'Age', 'City', 'Salary'], dtype='str')
Name        str
Age       int64
City        str
Salary    int64
dtype: object
0    Dipali
1       Anu
2     Manas
3     anush
4      lila
Name: Name, dtype: str
     Name  Age
0  Dipali   24
1     Anu   25
2   Manas   26
3   anush   28
4    lila   31

In [55]:
#10. Access Specific Row
'''print(df.iloc[2])
print(df.iloc[:,2])
print(df['Name'].iloc[1])
print(df.iloc[1:2])
print(df.iloc[0:4])
print(df.iloc[0])
print()'''
print(df)
print()
#Q11. Access Specific Value
print(df.iloc[2,1])

     Name  Age      City  Salary
0  Dipali   24      pune   20000
1     Anu   25     kalaj   10000
2   Manas   26  phalatan   15000
3   anush   28  baramati   16000
4    lila   31    satara    5000

26

In [56]:
#11. Filter Rows
print(df[df['Salary']>10000])
print(df[df['Age']>24])
print(df[df['Name']=='Dipali'])
print(df[df['Salary']<15000])
print(df[(df['Salary']>10000) & (df['Age'] <=24)])
print(df[(df['Salary']<=15000) | (df['Age'] >=21) ])

     Name  Age      City  Salary
0  Dipali   24      pune   20000
2   Manas   26  phalatan   15000
3   anush   28  baramati   16000
    Name  Age      City  Salary
1    Anu   25     kalaj   10000
2  Manas   26  phalatan   15000
3  anush   28  baramati   16000
4   lila   31    satara    5000
     Name  Age  City  Salary
0  Dipali   24  pune   20000
   Name  Age    City  Salary
1   Anu   25   kalaj   10000
4  lila   31  satara    5000
     Name  Age  City  Salary
0  Dipali   24  pune   20000
     Name  Age      City  Salary
0  Dipali   24      pune   20000
1     Anu   25     kalaj   10000
2   Manas   26  phalatan   15000
3   anush   28  baramati   16000
4    lila   31    satara    5000

The error occurs because Python does not use not directly between two Pandas conditions.

print(df[(df['Salary']<=15000) not (df['Age'] >=21) ])

In [57]:
### 12. Sort Data
df['Age'].sort_values()

0    24
1    25
2    26
3    28
4    31
Name: Age, dtype: int64

In [58]:
### 13. Rename Columns
df.rename(columns={'Age' :'Employee_Age'}, inplace=False)
df.rename(columns={'Name' : 'Employee_name'}, inplace=False)
df.rename(columns={'City':'Employee_City'},inplace=True)
print(df)

     Name  Age Employee_City  Salary
0  Dipali   24          pune   20000
1     Anu   25         kalaj   10000
2   Manas   26      phalatan   15000
3   anush   28      baramati   16000
4    lila   31        satara    5000

In [59]:
### 14. Add New Column
df['Bonus']=[100,200,200,50,100]
print(df)

     Name  Age Employee_City  Salary  Bonus
0  Dipali   24          pune   20000    100
1     Anu   25         kalaj   10000    200
2   Manas   26      phalatan   15000    200
3   anush   28      baramati   16000     50
4    lila   31        satara    5000    100

In [60]:
### 15. Delete Column
df.drop(columns=['Bonus'],inplace=False)
df.drop(columns=['Age'],inplace=False)
df.drop(columns=['Name','Salary'],inplace=False)

   Age Employee_City  Bonus
0   24          pune    100
1   25         kalaj    200
2   26      phalatan    200
3   28      baramati     50
4   31        satara    100

In [61]:
df.loc[1,'Age']=np.nan
df.loc[2,'Salary']=np.nan
df.loc[4,'Age']=np.nan
df.loc[3,'Salary']=np.nan
print(df)
#df.drop(columns=['salary'],inplace=True)
df

     Name   Age Employee_City   Salary  Bonus
0  Dipali  24.0          pune  20000.0    100
1     Anu   NaN         kalaj  10000.0    200
2   Manas  26.0      phalatan      NaN    200
3   anush  28.0      baramati      NaN     50
4    lila   NaN        satara   5000.0    100

     Name   Age Employee_City   Salary  Bonus
0  Dipali  24.0          pune  20000.0    100
1     Anu   NaN         kalaj  10000.0    200
2   Manas  26.0      phalatan      NaN    200
3   anush  28.0      baramati      NaN     50
4    lila   NaN        satara   5000.0    100

In [62]:
### 16. Count Missing Values
print(df.isnull().sum())

Name             0
Age              2
Employee_City    0
Salary           2
Bonus            0
dtype: int64

In [63]:
### 17. Fill Missing Values
print(df.fillna(0))

     Name   Age Employee_City   Salary  Bonus
0  Dipali  24.0          pune  20000.0    100
1     Anu   0.0         kalaj  10000.0    200
2   Manas  26.0      phalatan      0.0    200
3   anush  28.0      baramati      0.0     50
4    lila   0.0        satara   5000.0    100

In [64]:
### 18. Drop Missing Values
print(df.dropna())

     Name   Age Employee_City   Salary  Bonus
0  Dipali  24.0          pune  20000.0    100

In [65]:
### 19. Find Unique Values
print(df['Employee_City'].unique())
print(df['Bonus'].unique())
print(df['Age'].unique())

<StringArray>
['pune', 'kalaj', 'phalatan', 'baramati', 'satara']
Length: 5, dtype: str
[100 200  50]
[24. nan 26. 28.]

In [66]:
### 20. Basic Statistics
df['mean']=df['Salary'].mean()
df['max']=df['Salary'].max()
df['min']=df['Salary'].min()

df

     Name   Age Employee_City   Salary  Bonus          mean      max     min
0  Dipali  24.0          pune  20000.0    100  11666.666667  20000.0  5000.0
1     Anu   NaN         kalaj  10000.0    200  11666.666667  20000.0  5000.0
2   Manas  26.0      phalatan      NaN    200  11666.666667  20000.0  5000.0
3   anush  28.0      baramati      NaN     50  11666.666667  20000.0  5000.0
4    lila   NaN        satara   5000.0    100  11666.666667  20000.0  5000.0

# 🟡 Intermediate Level (21-50)

Focus: GroupBy, Merge, Pivot Tables, String Operations.

Grouping by Bonus is fine if that's the column available.


Use transform('mean') if you want the result stored back into a new column.

transform() performs a group-wise calculation and returns a result with the same number of rows as the original DataFrame.

In [67]:
### 21. Group Employees by Department
avg=df.groupby('Bonus' ).agg({'Salary' : 'mean'})
print(avg)
#this fun explanationOnly 2 rows (one for each Bonus group).
#Original DataFrame had 4 rows.

#That's why you cannot directly assign this to df['avg'].

        Salary
Bonus
50         NaN
100    12500.0
200    10000.0

In [68]:
#using transformer
df['avg']=df.groupby('Bonus')['Salary'].transform('mean')
avg=df.groupby('Name')['Salary'].transform('sum')
print(avg)
df

0    20000.0
1    10000.0
2        0.0
3        0.0
4     5000.0
Name: Salary, dtype: float64

,Name,Age,Employee_City,Salary,Bonus,mean,max,min,avg
0,Dipali,24.0,pune,20000.0,100,11666.666667,20000.0,5000.0,12500.0
1,Anu,NaN,kalaj,10000.0,200,11666.666667,20000.0,5000.0,10000.0
2,Manas,26.0,phalatan,NaN,200,11666.666667,20000.0,5000.0,10000.0
3,anush,28.0,baramati,NaN,50,11666.666667,20000.0,5000.0,NaN
4,lila,NaN,satara,5000.0,100,11666.666667,20000.0,5000.0,12500.0

In [69]:
### 22. Count Employees per Department
count=df.groupby('Name')['Age'].count()
print(count)

Name
Anu       0
Dipali    1
Manas     1
anush     1
lila      0
Name: Age, dtype: int64

In [70]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Emp_ID': [101, 102, 103, 104, 105, 106, 107, 108],
    'Name': ['Dipali', 'Anu', 'Manas', 'Om', 'Riya', 'Kunal', 'Neha', 'Amit'],
    'Department': ['HR', 'IT', 'IT', 'Finance', 'HR', 'Finance', 'IT', 'HR'],
    'City': ['Pune', 'Mumbai', 'Pune', 'Delhi', 'Mumbai', 'Pune', 'Delhi', 'Pune'],
    'Age': [24, 26, np.nan, 30, 25, 28, np.nan, 27],
    'Salary': [40000, 60000, 55000, 70000, 45000, np.nan, 65000, 50000],
    'Bonus': [5000, 8000, 7000, 9000, 6000, 8500, 7500, 5500]
})

print(df)

   Emp_ID    Name Department    City   Age   Salary  Bonus
0     101  Dipali         HR    Pune  24.0  40000.0   5000
1     102     Anu         IT  Mumbai  26.0  60000.0   8000
2     103   Manas         IT    Pune   NaN  55000.0   7000
3     104      Om    Finance   Delhi  30.0  70000.0   9000
4     105    Riya         HR  Mumbai  25.0  45000.0   6000
5     106   Kunal    Finance    Pune  28.0      NaN   8500
6     107    Neha         IT   Delhi   NaN  65000.0   7500
7     108    Amit         HR    Pune  27.0  50000.0   5500

In [71]:
### 22. Count Employees per Department
count=df.groupby('Department')['Emp_ID'].count()
print(count)

#another way
coun1=df.groupby('Department').size()
print(coun1)

Department
Finance    2
HR         3
IT         3
Name: Emp_ID, dtype: int64
Department
Finance    2
HR         3
IT         3
dtype: int64

In [72]:
### 23. Multiple Aggregations
aggg=pd.pivot_table(df , values='Salary', index='Department', aggfunc=['mean','max','min'])
print(aggg)

#using group by
df.groupby('Department')['Salary'].agg(['mean','max','min'])

               mean      max      min
             Salary   Salary   Salary
Department
Finance     70000.0  70000.0  70000.0
HR          45000.0  50000.0  40000.0
IT          60000.0  65000.0  55000.0

               mean      max      min
Department
Finance     70000.0  70000.0  70000.0
HR          45000.0  50000.0  40000.0
IT          60000.0  65000.0  55000.0

In [73]:
### 24. Value Counts
df.groupby('City').count()

        Emp_ID  Name  Department  Age  Salary  Bonus
City
Delhi        2     2           2    1       2      2
Mumbai       2     2           2    2       2      2
Pune         4     4           4    3       3      4

In [1]:
### 25. Merge Two DataFrames
import pandas as pd

employees = pd.DataFrame({
    'Emp_ID': [101, 102, 103, 104, 105],
    'Name': ['Dipali', 'Anu', 'Manas', 'Om', 'Riya'],
    'Department': ['HR', 'IT', 'IT', 'Finance', 'HR'],
    'Salary': [40000, 60000, 55000, 70000, 45000]
})

print(employees)

cities = pd.DataFrame({
    'Emp_ID': [101, 102, 103, 106, 107],
    'City': ['Pune', 'Mumbai', 'Delhi', 'Satara', 'Kolhapur']
})

print(cities)

# ── left join (default) ───────────────────────────────────────────
#print("\n--- left join (keep all left rows) ---")
#print(df_left.join(df_right, how="left"))

# ── left join (default) ───────────────────────────────────────────
print("\n--- left join (keep all left rows) ---")
print(employees.join(cities, how="left"))

   Emp_ID    Name Department  Salary
0     101  Dipali         HR   40000
1     102     Anu         IT   60000
2     103   Manas         IT   55000
3     104      Om    Finance   70000
4     105    Riya         HR   45000
   Emp_ID      City
0     101      Pune
1     102    Mumbai
2     103     Delhi
3     106    Satara
4     107  Kolhapur

--- left join (keep all left rows) ---

ValueError: columns overlap but no suffix specified: Index(['Emp_ID'], dtype='str')