In [5]:
### Q1. Create a Pandas Series from a list of integers.
import pandas as pd
df=pd.Series([1,2,3,4,5,6])
print(df)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [6]:
### Q2. Create a Series from a dictionary with custom index.
data={'dipali':10 , 'anu':20,'manas':89}
ser=pd.Series(data , index=['dipali','anu','manas','d'])
print(ser)

dipali    10.0
anu       20.0
manas     89.0
d          NaN
dtype: float64

In [9]:
df=pd.DataFrame({
    'name':['dipali','anu','anamika'],
    'marks':[90,97,98],
    'age':[22,23,21]
})
df

      name  marks  age
0   dipali     90   22
1      anu     97   23
2  anamika     98   21

In [11]:
### Q3. Access elements using index labels.
#=================for single value==============
print(df['marks'])
print()

#========= accesse multiple values =================
print(df[['age','marks']])
print()

#========== range of labels ===============
print(df.loc[:,'marks':'age'])

0    90
1    97
2    98
Name: marks, dtype: int64

   age  marks
0   22     90
1   23     97
2   21     98

   marks  age
0     90   22
1     97   23
2     98   21

In [ ]:
### Q4. Perform arithmetic operations on a Series.
# **Hint:** Use `+`, `-`, `*`, `/`, `//`, `%`, `**` directly on the Series. Operations are **element-wise** and **index-aligned**.
df_m1=df.copy()
print('======= additoin operator=========')
df_m1['marks']=df_m1['marks']+5
print(df_m1)

print("==============subtraction operator======")
df_m1['age']=df_m1['age']-1
print(df_m1)

print('============ multiplication operator ===========')
df1=pd.Series([10,20,30])
df2=pd.Series([40,50,60])
print(df1*df2)

print('======= divison operator ===========')
df_m1['marks']=df_m1['marks']/2
print(df_m1['marks'])

print("========= floor division=========")
print(df1//df2)
df_m1['marks']=df_m1['marks']//3
print(df_m1['marks'])

print("======== Modulus ========")
df_m1['marks']=df_m1["marks"]%2
print(df_m1['marks'])

print("====== Exponentiation ========")
print(df1**df2)

print("===== index wise==========")
df1=pd.Series([10,20,30],index=['A','B','C'])
df2=pd.Series([40,50,60],index=['A','B','C'])
print(df1+df2)

======= additoin operator=========
  student_name  marks  age
0         jhon     95   23
1        alice     83   23
2          bob     50   22
3          mia     83   21
4         meer     93   24
==============subtraction operator======
  student_name  marks  age
0         jhon     95   22
1        alice     83   22
2          bob     50   21
3          mia     83   20
4         meer     93   23
============ multiplication operator ===========
0     400
1    1000
2    1800
dtype: int64
======= divison operator ===========
0    47.5
1    41.5
2    25.0
3    41.5
4    46.5
Name: marks, dtype: float64
========= floor division=========
0    0
1    0
2    0
dtype: int64
0    15.0
1    13.0
2     8.0
3    13.0
4    15.0
Name: marks, dtype: float64
======== Modulus ========
0    1.0
1    1.0
2    0.0
3    1.0
4    1.0
Name: marks, dtype: float64
====== Exponentiation ========
0   -5047021154770878464
1                      0
2    1152921504606846976
dtype: int64
===== index wise==========
A    50
B    70
C    90
dtype: int64

In [ ]:
### Q5. Find mean, min, max of a Series.
print("====== mean ======")
mean=df1.mean()
print(mean)

print("======== minimum ===========")
minm=df2.min()
print(minm)

print("======== minimum ===========")
max=df2.max()
print(max)

print("======== minimum ===========")
summ=df2.sum()
print(summ)

print("======== minimum ===========")
median=df2.median()
print(median)

print("======== minimum ===========")
sdt=df2.std()
print(sdt)

====== mean ======
20.0
======== minimum ===========
40
======== minimum ===========
60
======== minimum ===========
150
======== minimum ===========
50.0
======== minimum ===========
10.0

In [ ]:
### Q6. Apply conditional filtering on a Series.
boolean_masking=df[df['age'] >= 23 ]
print(boolean_masking)

maskin=df[(df['marks'] >= 90) & (df['age']>=23)]
print(maskin)
print()
or_masking=df[(df['marks'] >=80) | (df['age'] >= 23)]
print(or_masking)

  student_name  marks  age
0         jhon     90   23
1        alice     78   23
4         meer     88   24
  student_name  marks  age
0         jhon     90   23

  student_name  marks  age
0         jhon     90   23
1        alice     78   23
4         meer     88   24

In [ ]:
### Q7. Replace values in a Series.
replce=df.replace(90,99)
print(replce)

replced_dict=df.replace({'jhon':'johan','bob':'Bob'})
print(replced_dict)

  student_name  marks  age
0         jhon     99   23
1        alice     78   23
2          bob     45   22
3          mia     78   21
4         meer     88   24
  student_name  marks  age
0        johan     90   23
1        alice     78   23
2          Bob     45   22
3          mia     78   21
4         meer     88   24

In [ ]:
### Q8. Convert Series data type.
convert=df['marks'].astype(float)
print(convert)

print()
convert_str=df['marks'].astype(str)
print(convert_str)

print()
convert_ca=df['marks'].astype("category")
print(convert_ca)

convert_int=df['marks'].astype(int)
print(convert_int)

0    90.0
1    78.0
2    45.0
3    78.0
4    88.0
Name: marks, dtype: float64

0    90
1    78
2    45
3    78
4    88
Name: marks, dtype: str

0    90
1    78
2    45
3    78
4    88
Name: marks, dtype: category
Categories (4, int64): [45, 78, 88, 90]
0    90
1    78
2    45
3    78
4    88
Name: marks, dtype: int64

In [ ]:
### Q9. Check for null values in Series.
import numpy as np
import pandas as pd
dfnull=pd.DataFrame({
    'student_name':[None,'jhon','alice',None,'bob',None,'mia','meer'],
    'marks':[90,None,78,45,78,None,88,None],
    'age':[23,23,None,22,21,None,24,None]
})
print(dfnull.isnull())
print(dfnull.isnull().sum())

   student_name  marks    age
0          True  False  False
1         False   True  False
2         False  False   True
3          True  False  False
4         False  False  False
5          True   True   True
6         False  False  False
7         False   True   True
student_name    3
marks           3
age             3
dtype: int64

In [ ]:
### Q10. Fill missing values in Series.
print(dfnull.fillna(0))
print(dfnull['marks'].fillna(dfnull['marks'].mean()))
print(dfnull.ffill())
print(dfnull.bfill)

  student_name  marks   age
0            0   90.0  23.0
1         jhon    0.0  23.0
2        alice   78.0   0.0
3            0   45.0  22.0
4          bob   78.0  21.0
5            0    0.0   0.0
6          mia   88.0  24.0
7         meer    0.0   0.0
0    90.0
1    75.8
2    78.0
3    45.0
4    78.0
5    75.8
6    88.0
7    75.8
Name: marks, dtype: float64
  student_name  marks   age
0          NaN   90.0  23.0
1         jhon   90.0  23.0
2        alice   78.0  23.0
3        alice   45.0  22.0
4          bob   78.0  21.0
5          bob   78.0  21.0
6          mia   88.0  24.0
7         meer   88.0  24.0
<bound method NDFrame.bfill of   student_name  marks   age
0          NaN   90.0  23.0
1         jhon    NaN  23.0
2        alice   78.0   NaN
3          NaN   45.0  22.0
4          bob   78.0  21.0
5          NaN    NaN   NaN
6          mia   88.0  24.0
7         meer    NaN   NaN>

In [ ]:
### Q11. Create DataFrame from a list.
data=[
    ['lisa',24,'25_days',12000],
    ['Bob',23,'20_days',10000],
    ['riya',25,'29_days',15000],
    ['manas',22,'30_days',20000]
]
list_data=pd.DataFrame(data,columns=['Employee_name','Employee_age','working_day','Salary'])
print(list_data)

  Employee_name  Employee_age working_day  Salary
0          lisa            24     25_days   12000
1           Bob            23     20_days   10000
2          riya            25     29_days   15000
3         manas            22     30_days   20000

In [ ]:
### Q12. Create DataFrame from a dictionary.
names=pd.Series(['manas','Anu','ashwini'])
ages=pd.Series([24,0,22])
marks=pd.Series([90,98,99])
df3=pd.DataFrame({"Name":names,"Age":ages ,"MArks":marks})
print(df3)

      Name  Age  MArks
0    manas   24     90
1      Anu    0     98
2  ashwini   22     99

In [ ]:
### Q13. Create DataFrame from list of dictionaries.
import pandas as pd
import numpy as np
data=[
    {"student_name":'dipali' ,"Age":23 ,'Marks':98},
    {"student_name":'dip' ,"Age":22 ,'Marks':95},
    {"student_name":'Anu' ,"Age":21 ,'Marks':80},
    {"student_name":'Manas' ,"Age":20 ,'Marks':90}
]
df2=pd.DataFrame(data)
print(df2)

  student_name  Age  Marks
0       dipali   23     98
1          dip   22     95
2          Anu   21     80
3        Manas   20     90

In [ ]:
### Q14. Display DataFrame structure (shape, columns, dtypes).
print("shape of the DataFrame :",df2.shape)
print("Columns of the DataFrame :",df2.columns)
print("dtypes of the DataFrame : ",df2.dtypes)
print("info of the DtaFrame :",df2.info())
print("describe the DataFrame : ",df2.describe())

shape of the DataFrame : (4, 3)
Columns of the DataFrame : Index(['student_name', 'Age', 'Marks'], dtype='str')
dtypes of the DataFrame :  student_name      str
Age             int64
Marks           int64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student_name  4 non-null      str
 1   Age           4 non-null      int64
 2   Marks         4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes
info of the DtaFrame : None
describe the DataFrame :               Age      Marks
count   4.000000   4.000000
mean   21.500000  90.750000
std     1.290994   7.889867
min    20.000000  80.000000
25%    20.750000  87.500000
50%    21.500000  92.500000
75%    22.250000  95.750000
max    23.000000  98.000000

In [ ]:
### Q15. Select single column from DataFrame.
print("single column :",df2['Age'])
print(df2.Age)

single column : 0    23
1    22
2    21
3    20
Name: Age, dtype: int64
0    23
1    22
2    21
3    20
Name: Age, dtype: int64

In [ ]:
### Q16. Select multiple columns.
print("multiple columns : ",df2[['Age','student_name']])
print()
print(df2)

multiple columns :     Age student_name
0   23       dipali
1   22          dip
2   21          Anu
3   20        Manas

  student_name  Age  Marks
0       dipali   23     98
1          dip   22     95
2          Anu   21     80
3        Manas   20     90

In [ ]:
### Q17. Add new column with scalar value.
df2['class']='BCS'
print("Adding new column : ")
print(df2)

Adding new column :
  student_name  Age  Marks class
0       dipali   23     98   BCS
1          dip   22     95   BCS
2          Anu   21     80   BCS
3        Manas   20     90   BCS

In [ ]:
### Q18. Add column using Series.
df2['year']=pd.Series([2025,2024,2026])
print(df2)

  student_name  Age  Marks class    year
0       dipali   23     98   BCS  2025.0
1          dip   22     95   BCS  2024.0
2          Anu   21     80   BCS  2026.0
3        Manas   20     90   BCS     NaN

In [ ]:
### Q19. Rename columns using `rename()`.
df2.rename(columns={"Age":"Student_age"},inplace=True)
print(df2)

  student_name  Student_age  Marks class    year
0       dipali           23     98   BCS  2025.0
1          dip           22     95   BCS  2024.0
2          Anu           21     80   BCS  2026.0
3        Manas           20     90   BCS     NaN

In [ ]:
### Q20. Rename multiple columns.
df2.rename(columns={"Marks":"Student_Marks", "class":"Student_class"},inplace=True)
print(df2)

  student_name  Student_age  Student_Marks Student_class    year
0       dipali           23             98           BCS  2025.0
1          dip           22             95           BCS  2024.0
2          Anu           21             80           BCS  2026.0
3        Manas           20             90           BCS     NaN

## 🔹 Section 2: Indexing, Selection & Slicing (Q21–Q40)

In [ ]:
### Q21. Select rows using `loc`.
print(df2.loc[0])
print(df2.loc[0 : 3])

student_name     dipali
Student_age          23
Student_Marks        98
Student_class       BCS
year             2025.0
Name: 0, dtype: object
  student_name  Student_age  Student_Marks Student_class    year
0       dipali           23             98           BCS  2025.0
1          dip           22             95           BCS  2024.0
2          Anu           21             80           BCS  2026.0
3        Manas           20             90           BCS     NaN

In [ ]:
### Q22. Select rows using `iloc`.
print(df2.iloc[0])
print(df2.iloc[0:4])

student_name     dipali
Student_age          23
Student_Marks        98
Student_class       BCS
year             2025.0
Name: 0, dtype: object
  student_name  Student_age  Student_Marks Student_class    year
0       dipali           23             98           BCS  2025.0
1          dip           22             95           BCS  2024.0
2          Anu           21             80           BCS  2026.0
3        Manas           20             90           BCS     NaN

In [ ]:
### Q23. Access specific row and column.
print(df2.loc[0,'Student_Marks'])
print(df2.loc[3,'student_name'])

98
Manas

In [ ]:
### Q24. Select subset using multiple rows & columns.
data1=pd.DataFrame({
   "names": ['lisa','Bob','riya','manas'],
   "age": [20,23,24,25],
    "Salary":[10000,15000,20000,15000],
    "city":['pune','mumbai','baramati','phaltan']
},index=['d1','d2','d3','d4'])

print(data1.loc[['d1','d4'],['names','city']])
print(data1.iloc[[0,2],[0,3]])

    names     city
d1   lisa     pune
d4  manas  phaltan
   names      city
d1  lisa      pune
d3  riya  baramati

In [ ]:
### Q25. Apply conditional filtering using `loc`.
print(data1.loc[data1['age'] > 20 ,['names','Salary','age']])
print(data1.loc[(data1['Salary']>15000) & (data1['age']>20)])
print(data1.loc[(data1['Salary']>15000) | (data1['age']>20)])
print(data1.loc[(data1['names']=='lisa') | (data1['age']==20)])

    names  Salary  age
d2    Bob   15000   23
d3   riya   20000   24
d4  manas   15000   25
   names  age  Salary      city
d3  riya   24   20000  baramati
    names  age  Salary      city
d2    Bob   23   15000    mumbai
d3   riya   24   20000  baramati
d4  manas   25   15000   phaltan
   names  age  Salary  city
d1  lisa   20   10000  pune

In [ ]:
### Q26. Slice rows using index range.
print(data1.iloc[2:4])
print(data1.iloc[0:3])
print(data1.iloc[1:1])
print()
print("data using index")
print(data1.loc['d1':'d2'])

    names  age  Salary      city
d3   riya   24   20000  baramati
d4  manas   25   15000   phaltan
   names  age  Salary      city
d1  lisa   20   10000      pune
d2   Bob   23   15000    mumbai
d3  riya   24   20000  baramati
Empty DataFrame
Columns: [names, age, Salary, city]
Index: []

data using index
   names  age  Salary    city
d1  lisa   20   10000    pune
d2   Bob   23   15000  mumbai

In [ ]:
### Q27. Slice columns using labels.
print(data1.loc[:,'names':'Salary'])
#if we use the sliceing on columns it returns selected columns between this labels
print(data1.loc[:,'names':'city'])

    names  age  Salary
d1   lisa   20   10000
d2    Bob   23   15000
d3   riya   24   20000
d4  manas   25   15000
    names  age  Salary      city
d1   lisa   20   10000      pune
d2    Bob   23   15000    mumbai
d3   riya   24   20000  baramati
d4  manas   25   15000   phaltan

In [ ]:
### Q28. Slice columns using position.
#selects all rows, columns at positions 1, 2, 3.
print(data1.iloc[:,1:4])
print(data1.iloc[1:4])

    age  Salary      city
d1   20   10000      pune
d2   23   15000    mumbai
d3   24   20000  baramati
d4   25   15000   phaltan
    names  age  Salary      city
d2    Bob   23   15000    mumbai
d3   riya   24   20000  baramati
d4  manas   25   15000   phaltan

In [ ]:
### Q29. Perform combined row & column slicing.
print(data1.loc['d1',['names','age']])
print(data1.iloc[0:3,[0,2,3]])

names    lisa
age        20
Name: d1, dtype: object
   names  Salary      city
d1  lisa   10000      pune
d2   Bob   15000    mumbai
d3  riya   20000  baramati

In [ ]:
### Q30. Set a column as index.
print(data1.set_index('names'))

       age  Salary      city
names
lisa    20   10000      pune
Bob     23   15000    mumbai
riya    24   20000  baramati
manas   25   15000   phaltan

In [ ]:
### Q31. Create hierarchical index (MultiIndex).
print(data1.set_index(['Salary','age']))

            names      city
Salary age
10000  20    lisa      pune
15000  23     Bob    mumbai
20000  24    riya  baramati
15000  25   manas   phaltan

In [ ]:
### Q32. Reset index.
import numpy as np
import pandas as pd
print(data1.reset_index(inplace=True))

None

In [ ]:
### Q33. Reset multi-index.
print(data1.reset_index())

   level_0 index  names  age  Salary      city
0        0    d1   lisa   20   10000      pune
1        1    d2    Bob   23   15000    mumbai
2        2    d3   riya   24   20000  baramati
3        3    d4  manas   25   15000   phaltan

In [ ]:
### Q34. Convert index to column.
print(data1.reset_index())

   level_0 index  names  age  Salary      city
0        0    d1   lisa   20   10000      pune
1        1    d2    Bob   23   15000    mumbai
2        2    d3   riya   24   20000  baramati
3        3    d4  manas   25   15000   phaltan

In [ ]:
### Q35. Use drop option in `reset_index`.
print(data1.reset_index(drop=True))
#print(data1.reset_index(drop=True,inplace=True))

  index  names  age  Salary      city
0    d1   lisa   20   10000      pune
1    d2    Bob   23   15000    mumbai
2    d3   riya   24   20000  baramati
3    d4  manas   25   15000   phaltan

In [ ]:
import pandas as pd

data = {
    'Name': ['Amit', 'Priya', 'Rahul'],
    'Age': [21, 22, 23],
    'Salary': [25000, 30000, 35000]
}

df = pd.DataFrame(data, index=['A', 'B', 'C'])

print(df)

    Name  Age  Salary
A   Amit   21   25000
B  Priya   22   30000
C  Rahul   23   35000

In [ ]:
### Q36. Perform label-based indexing.
print(data1.loc['d1'])

#print(df.loc['A'])

KeyError: 'd1'

In [ ]:
### Q37. Perform position-based indexing.
print(data1.iloc[0])
print()
print(data1.iloc[:2])
print()
print(data1.iloc[2:])

names      lisa
age          20
Salary    10000
city       pune
Name: d1, dtype: object

   names  age  Salary    city
d1  lisa   20   10000    pune
d2   Bob   23   15000  mumbai

    names  age  Salary      city
d3   riya   24   20000  baramati
d4  manas   25   15000   phaltan

In [ ]:
### Q38. Access first N rows.
print(data1.head(2))

   names  age  Salary    city
d1  lisa   20   10000    pune
d2   Bob   23   15000  mumbai

In [ ]:
### Q39. Access last N rows.
print(data1.tail(1))

    names  age  Salary     city
d4  manas   25   15000  phaltan

In [ ]:
### Q40. Extract random sample from DataFrame.
print(data1.sample(n=0,random_state=42))
print()
print(data1.sample(frac=0.2,random_state=42))
print()

Empty DataFrame
Columns: [names, age, Salary, city]
Index: []

   names  age  Salary    city
d2   Bob   23   15000  mumbai

## 🔹 Section 3: Data Cleaning (Q41–Q60)

In [ ]:
import pandas as pd
dfnull1=pd.DataFrame({
    'student_name':[None,'jhon',None,None,'bob',None,'mia','meer'],
    'marks':[90,None,78,45,78,None,88,None],
    'age':[23,23,None,22,21,None,24,None]
})

In [ ]:
### Q41. Detect missing values using `isnull()`.
print(dfnull1.isnull())

   student_name  marks    age
0          True  False  False
1         False   True  False
2         False  False   True
3          True  False  False
4         False  False  False
5          True   True   True
6         False  False  False
7         False   True   True

In [ ]:
### Q42. Drop missing values using `dropna()`.
print(dfnull1.dropna(subset=['marks']))
print(dfnull1.dropna(axis=1, thresh=5))
#df.dropna(axis=1, thresh=5) removes columns that contain fewer than 5 non-missing (non-NaN) values.
print(dfnull1.count())

  student_name  marks   age
0          NaN   90.0  23.0
2          NaN   78.0   NaN
3          NaN   45.0  22.0
4          bob   78.0  21.0
6          mia   88.0  24.0
   marks   age
0   90.0  23.0
1    NaN  23.0
2   78.0   NaN
3   45.0  22.0
4   78.0  21.0
5    NaN   NaN
6   88.0  24.0
7    NaN   NaN
student_name    4
marks           5
age             5
dtype: int64

In [ ]:
### Q43. Fill missing values with a constant.
print(dfnull1['marks'].fillna(99))
print(dfnull1.fillna(0))

0    90.0
1    99.0
2    78.0
3    45.0
4    78.0
5    99.0
6    88.0
7    99.0
Name: marks, dtype: float64
  student_name  marks   age
0            0   90.0  23.0
1         jhon    0.0  23.0
2            0   78.0   0.0
3            0   45.0  22.0
4          bob   78.0  21.0
5            0    0.0   0.0
6          mia   88.0  24.0
7         meer    0.0   0.0

In [ ]:
### Q44. Fill missing values using mean/median.
print(dfnull1['marks'].fillna(dfnull1['marks'].mean()))
print(dfnull1['age'].fillna(dfnull1['age'].median()))

0    90.0
1    75.8
2    78.0
3    45.0
4    78.0
5    75.8
6    88.0
7    75.8
Name: marks, dtype: float64
0    23.0
1    23.0
2    23.0
3    22.0
4    21.0
5    23.0
6    24.0
7    23.0
Name: age, dtype: float64

In [ ]:
### Q45. Use forward fill and backward fill.
print(dfnull1.ffill())
print(dfnull1.bfill())
#Fill NaN using the next valid value below it.

  student_name  marks   age
0          NaN   90.0  23.0
1         jhon   90.0  23.0
2         jhon   78.0  23.0
3         jhon   45.0  22.0
4          bob   78.0  21.0
5          bob   78.0  21.0
6          mia   88.0  24.0
7         meer   88.0  24.0
  student_name  marks   age
0         jhon   90.0  23.0
1         jhon   78.0  23.0
2          bob   78.0  22.0
3          bob   45.0  22.0
4          bob   78.0  21.0
5          mia   88.0  24.0
6          mia   88.0  24.0
7         meer    NaN   NaN

In [ ]:
### Q46. Convert data type using `astype()`.\
print(dfnull1['marks'].astype(float))
print(dfnull1['student_name'].astype("category"))

0    90.0
1     NaN
2    78.0
3    45.0
4    78.0
5     NaN
6    88.0
7     NaN
Name: marks, dtype: float64
0     NaN
1    jhon
2     NaN
3     NaN
4     bob
5     NaN
6     mia
7    meer
Name: student_name, dtype: category
Categories (4, str): ['bob', 'jhon', 'meer', 'mia']

In [ ]:
#for errors="coerce"` inside `pd.to_numeric()`
dfnull2=pd.DataFrame({
    'marks' :['10','20','30','40']
})
print()
dfnull2['marks']=pd.to_numeric(dfnull2['marks'], errors="coerce")
print(dfnull2)

   marks
0     10
1     20
2     30
3     40

In [ ]:
### Q47. Clean string column using `.str.lower()`.
print(dfnull1['student_name'].str.lower())
print(dfnull1['student_name'].str.upper())
print(dfnull1['student_name'].str.title())

0     NaN
1    jhon
2     NaN
3     NaN
4     bob
5     NaN
6     mia
7    meer
Name: student_name, dtype: str
0     NaN
1    JHON
2     NaN
3     NaN
4     BOB
5     NaN
6     MIA
7    MEER
Name: student_name, dtype: str
0     NaN
1    Jhon
2     NaN
3     NaN
4     Bob
5     NaN
6     Mia
7    Meer
Name: student_name, dtype: str

In [ ]:
### Q48. Trim whitespace in strings.
print(dfnull1['student_name'].str.strip())
print(dfnull1['student_name'].str.lstrip())
print(dfnull1['student_name'].str.rstrip())

0     NaN
1    jhon
2     NaN
3     NaN
4     bob
5     NaN
6     mia
7    meer
Name: student_name, dtype: str
0     NaN
1    jhon
2     NaN
3     NaN
4     bob
5     NaN
6     mia
7    meer
Name: student_name, dtype: str
0     NaN
1    jhon
2     NaN
3     NaN
4     bob
5     NaN
6     mia
7    meer
Name: student_name, dtype: str

In [ ]:
### Q49. Replace substring in column.
print(dfnull1['student_name'].str.replace('jhon','johny'))

print(dfnull1['student_name'].str.replace('jhon','johny', regex=True))

0      NaN
1    johny
2      NaN
3      NaN
4      bob
5      NaN
6      mia
7     meer
Name: student_name, dtype: str
0      NaN
1    johny
2      NaN
3      NaN
4      bob
5      NaN
6      mia
7     meer
Name: student_name, dtype: str

In [ ]:
### Q50. Extract part of string using `.str`.
print(dfnull1['student_name'].str[:3])
print(dfnull1['student_name'].str.split("o").str[1])

0    NaN
1    jho
2    NaN
3    NaN
4    bob
5    NaN
6    mia
7    mee
Name: student_name, dtype: str
0    NaN
1      n
2    NaN
3    NaN
4      b
5    NaN
6    NaN
7    NaN
Name: student_name, dtype: object

In [ ]:
### Q51. Detect duplicate rows.
print(dfnull1.duplicated())
print(dfnull1.duplicated().sum())
print(dfnull1['marks'][dfnull1.duplicated()])
print(dfnull1[dfnull1.duplicated()])

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool
0
Series([], Name: marks, dtype: float64)
Empty DataFrame
Columns: [student_name, marks, age]
Index: []

In [ ]:
### Q52. Remove duplicates using `drop_duplicates()`.
print(dfnull1.drop_duplicates())
print(dfnull1.drop_duplicates(subset=['marks'],keep=False))
print(dfnull1.drop_duplicates(subset=['marks'], keep='first'))
print(dfnull1.drop_duplicates(subset=['marks'], keep='last'))


#subset=['col']: Checks duplicates only in the specified column(s).
#keep='first': Keeps the first occurrence of each duplicate group.
#keep='last': Keeps the last occurrence of each duplicate group.
#keep=False: Removes all duplicated rows, keeping only unique values.

  student_name  marks   age
0          NaN   90.0  23.0
1         jhon    NaN  23.0
2          NaN   78.0   NaN
3          NaN   45.0  22.0
4          bob   78.0  21.0
5          NaN    NaN   NaN
6          mia   88.0  24.0
7         meer    NaN   NaN
  student_name  marks   age
0          NaN   90.0  23.0
3          NaN   45.0  22.0
6          mia   88.0  24.0
  student_name  marks   age
0          NaN   90.0  23.0
1         jhon    NaN  23.0
2          NaN   78.0   NaN
3          NaN   45.0  22.0
6          mia   88.0  24.0
  student_name  marks   age
0          NaN   90.0  23.0
3          NaN   45.0  22.0
4          bob   78.0  21.0
6          mia   88.0  24.0
7         meer    NaN   NaN

In [ ]:
### Q53. Rename row labels.
print(dfnull1.rename(index={'d1':'di1'}))

  student_name  marks   age
0          NaN   90.0  23.0
1         jhon    NaN  23.0
2          NaN   78.0   NaN
3          NaN   45.0  22.0
4          bob   78.0  21.0
5          NaN    NaN   NaN
6          mia   88.0  24.0
7         meer    NaN   NaN

In [ ]:
### Q54. Handle inconsistent data.
print(dfnull1['student_name'].str.strip().str.lower())
print(dfnull1['student_name']
      .str.strip()
      .str.lower()
      .replace("s","*"))

0     NaN
1    jhon
2     NaN
3     NaN
4     bob
5     NaN
6     mia
7    meer
Name: student_name, dtype: str
0     NaN
1    jhon
2     NaN
3     NaN
4     bob
5     NaN
6     mia
7    meer
Name: student_name, dtype: str

In [ ]:
### Q55. Replace values in DataFrame.
print(dfnull1.replace('student_name','stud_name'))

  student_name  marks   age
0          NaN   90.0  23.0
1         jhon    NaN  23.0
2          NaN   78.0   NaN
3          NaN   45.0  22.0
4          bob   78.0  21.0
5          NaN    NaN   NaN
6          mia   88.0  24.0
7         meer    NaN   NaN

In [ ]:
print(dfnull1.replace(88.0, "8000"))
print(dfnull1.replace({"student_name":"stud_name"}))

  student_name marks   age
0          NaN  90.0  23.0
1         jhon   NaN  23.0
2          NaN  78.0   NaN
3          NaN  45.0  22.0
4          bob  78.0  21.0
5          NaN   NaN   NaN
6          mia  8000  24.0
7         meer   NaN   NaN
  student_name  marks   age
0          NaN   90.0  23.0
1         jhon    NaN  23.0
2          NaN   78.0   NaN
3          NaN   45.0  22.0
4          bob   78.0  21.0
5          NaN    NaN   NaN
6          mia   88.0  24.0
7         meer    NaN   NaN

In [ ]:
### Q56. Detect outliers in a column
import numpy as np
Q1=dfnull1['marks'].quantile(0.25)
print("Q1 : ",Q1)

Q3=dfnull1['marks'].quantile(0.75)
print("Q3 : ",Q3)
IQR=Q3-Q1
print("IQR : ",IQR)

lower_outliers =Q1-1.5*IQR
print("lower_outliers  : ",lower_outliers)
upper_outliers=Q3+1.5*IQR
print("upper_outliers :",upper_outliers)
outliers=dfnull1[
    (dfnull1['marks']< lower_outliers)|
    (dfnull1['marks']> upper_outliers)
]
print("outliers : ",outliers)


print("========= handle outliers using clip=====================")
### Q57. Handle outliers using clipping.
print(dfnull1['marks'].clip(lower=lower_outliers, upper=upper_outliers))

print("==================another method using mean ans std==================")
# another method using mean ans std
out_mean=dfnull1['marks'].mean()
print("mean : ",out_mean)
out_std=dfnull1['marks'].std()
print("std : ", out_std)
z_score=(dfnull1['marks']-out_mean)/out_std
print("Z_score: ",z_score)
out=dfnull1['marks'][np.abs(z_score)>3]
print("out : ", out)

Q1 :  78.0
Q3 :  88.0
IQR :  10.0
lower_outliers  :  63.0
upper_outliers : 103.0
outliers :    student_name  marks   age
3          NaN   45.0  22.0
========= handle outliers using clip=====================
0    90.0
1     NaN
2    78.0
3    63.0
4    78.0
5     NaN
6    88.0
7     NaN
Name: marks, dtype: float64
==================another method using mean ans std==================
mean :  75.8
std :  18.088670487352022
Z_score:  0    0.785022
1         NaN
2    0.121623
3   -1.702723
4    0.121623
5         NaN
6    0.674455
7         NaN
Name: marks, dtype: float64
out :  Series([], Name: marks, dtype: float64)

In [ ]:
### Q58. Standardize column names.
replace_nan=dfnull1.fillna(0)
print(replace_nan)
### Q58. Standardize column names.
replace_nan.columns=replace_nan.columns.str.strip().str.lower().str.replace(" ","_")
print(replace_nan.columns)

  student_name  marks   age
0            0   90.0  23.0
1         jhon    0.0  23.0
2            0   78.0   0.0
3            0   45.0  22.0
4          bob   78.0  21.0
5            0    0.0   0.0
6          mia   88.0  24.0
7         meer    0.0   0.0
Index(['student_name', 'marks', 'age'], dtype='str')

In [ ]:
### Q59. Handle mixed data types in a column.

print(pd.to_numeric(replace_nan["marks"], errors="coerce"))

0    90.0
1     0.0
2    78.0
3    45.0
4    78.0
5     0.0
6    88.0
7     0.0
Name: marks, dtype: float64

In [ ]:
### Q60. Remove special characters from text data.
df=pd.DataFrame({
    'subjects':['python','java','c++','html','css'],
    'marks':['90@','80@','90#','70%','60^']
})
print()
print(df['marks'].str.replace(r"[^a-zA-Z0-9]","", regex=True))

0    90
1    80
2    90
3    70
4    60
Name: marks, dtype: str

## 🔹 Section 4: Data Manipulation (Q61–Q80)

In [ ]:
### Q61. Filter rows using AND condition.
df=pd.DataFrame({
    'subjects':['python','java','c++','html','css'],
    'marks':[90,80,90,70,60]
})
print(df[(df['marks']>80) & (df['subjects']=='python')])

  subjects  marks
0   python     90

In [ ]:
### Q62. Filter rows using OR condition.
print(df[(df['marks'] > 80 ) | (df['subjects']=='python')])

  subjects  marks
0   python     90
2      c++     90

In [ ]:
### Q63. Filter rows using NOT condition.
print(df[~(df['marks']>80 )])

  subjects  marks
1     java     80
3     html     70
4      css     60

In [ ]:
### Q64. Sort DataFrame by column values.
print(dfnull1.sort_values('marks'))
print(dfnull1.sort_values(['marks', 'age']))

  student_name  marks   age
3          NaN   45.0  22.0
2          NaN   78.0   NaN
4          bob   78.0  21.0
6          mia   88.0  24.0
0          NaN   90.0  23.0
1         jhon    NaN  23.0
5          NaN    NaN   NaN
7         meer    NaN   NaN
  student_name  marks   age
3          NaN   45.0  22.0
4          bob   78.0  21.0
2          NaN   78.0   NaN
6          mia   88.0  24.0
0          NaN   90.0  23.0
1         jhon    NaN  23.0
5          NaN    NaN   NaN
7         meer    NaN   NaN

In [ ]:
### Q65. Sort DataFrame by index.
print(dfnull1.sort_index(axis=1))

    age  marks student_name
0  23.0   90.0          NaN
1  23.0    NaN         jhon
2   NaN   78.0          NaN
3  22.0   45.0          NaN
4  21.0   78.0          bob
5   NaN    NaN          NaN
6  24.0   88.0          mia
7   NaN    NaN         meer

In [ ]:
### Q66. Add calculated column.
dfnull1['total']=dfnull1['marks']*dfnull1['age']
print(dfnull1['total'])

dfnull1.assign(total=lambda x :dfnull1['marks']*dfnull1['age'])

0    2070.0
1       NaN
2       NaN
3     990.0
4    1638.0
5       NaN
6    2112.0
7       NaN
Name: total, dtype: float64

  student_name  marks   age   total
0          NaN   90.0  23.0  2070.0
1         jhon    NaN  23.0     NaN
2          NaN   78.0   NaN     NaN
3          NaN   45.0  22.0   990.0
4          bob   78.0  21.0  1638.0
5          NaN    NaN   NaN     NaN
6          mia   88.0  24.0  2112.0
7         meer    NaN   NaN     NaN

In [ ]:
### Q67. Remove column using `drop()`.
print(df.drop(columns=['marks']))

  subjects
0   python
1     java
2      c++
3     html
4      css

In [ ]:
### Q68. Remove rows using `drop()`.
print(df.drop(index=[0,3]))

  subjects  marks
1     java     80
2      c++     90
4      css     60

In [ ]:
### Q69. Use `map()` on a column.
df['update_marks']=df['marks'].map(lambda x : x+5)
print(df['update_marks'])

0    95
1    85
2    95
3    75
4    65
Name: update_marks, dtype: int64

In [ ]:
import pandas as pd
### Q70. Apply function using `apply()`.
#column -wise
df1=pd.DataFrame({
   ' marks' : [10,20,30,40,50,]
})
print(df1.apply(sum , axis=0))
print(df1.apply(np.mean, axis=1))

marks    150
dtype: int64
0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
dtype: float64

In [ ]:
### Q71. Apply element-wise using `applymap()` / `map()`.
#In recent versions of Pandas, applymap() has been removed and replaced with map() for DataFrames.

print(df1.map(np.median))

   marks
0   10.0
1   20.0
2   30.0
3   40.0
4   50.0

In [ ]:
### Q72. Chain multiple operations.
print(df.copy()
      .loc[df['marks']>=80]
      .sort_values(['marks'])
      .assign(student_marks=lambda x :x['marks']+5)
      .reset_index(drop=True))

  subjects  marks  update_marks  student_marks
0     java     80            85             85
1   python     90            95             95
2      c++     90            95             95

In [ ]:
### Q73. Normalize numeric columns (Min-Max).
print((dfnull1['marks'] - dfnull1['age'].min())/(dfnull1['marks'].max() - dfnull1['age'].min()))

0    1.000000
1         NaN
2    0.826087
3    0.347826
4    0.826087
5         NaN
6    0.971014
7         NaN
Name: marks, dtype: float64

In [ ]:
### Q74. Scale numerical data (Z-score standardization).
z_scors=(df['marks'] - df['marks'].mean() / df['marks'].std())
print(z_scors)

0    84.017673
1    74.017673
2    84.017673
3    64.017673
4    54.017673
Name: marks, dtype: float64

In [ ]:
### Q75. Rank values in a column.
print(df['marks'].rank())
print(df['marks'].rank(ascending=False))
print(df['marks'].rank(method="dense"))

0    4.5
1    3.0
2    4.5
3    2.0
4    1.0
Name: marks, dtype: float64
0    1.5
1    3.0
2    1.5
3    4.0
4    5.0
Name: marks, dtype: float64
0    4.0
1    3.0
2    4.0
3    2.0
4    1.0
Name: marks, dtype: float64

In [ ]:
print(df)

  subjects  marks  update_marks
0   python     90            95
1     java     80            85
2      c++     90            95
3     html     70            75
4      css     60            65

In [ ]:
### Q76. Create bins using `cut()`.
#cut() divides data into equal-width intervals.
print(pd.cut(df['marks'], bins=2))
print(pd.cut(df['marks'], bins=[0,25,50,75,100], labels=["low","mid","High","top"]))

0     (75.0, 90.0]
1     (75.0, 90.0]
2     (75.0, 90.0]
3    (59.97, 75.0]
4    (59.97, 75.0]
Name: marks, dtype: category
Categories (2, interval[float64, right]): [(59.97, 75.0] < (75.0, 90.0]]
0     top
1     top
2     top
3    High
4    High
Name: marks, dtype: category
Categories (4, str): ['low' < 'mid' < 'High' < 'top']

Function	Purpose

cut()	==> Creates equal-width intervals

qcut()	==> Creates equal-frequency (quantile) intervals

bins   ==> Defines interval boundaries

In [ ]:
### Q77. Create bins using `qcut()`.
#qcut() divides data into equal-frequency bins (quantiles).
#Each bin gets approximately the same number of observations.
#bins specifies how intervals are created.

df3=pd.DataFrame({
    'marks' : [10,20,30,40,50,60,70,80,90]
})
print(pd.qcut(df3['marks'],q=4))

0    (9.999, 30.0]
1    (9.999, 30.0]
2    (9.999, 30.0]
3     (30.0, 50.0]
4     (30.0, 50.0]
5     (50.0, 70.0]
6     (50.0, 70.0]
7     (70.0, 90.0]
8     (70.0, 90.0]
Name: marks, dtype: category
Categories (4, interval[float64, right]): [(9.999, 30.0] < (30.0, 50.0] < (50.0, 70.0] < (70.0, 90.0]]

In [ ]:
### Q78. Count unique values.
print(df['marks'].nunique())
print(df['marks'].value_counts())

4
marks
90    2
80    1
70    1
60    1
Name: count, dtype: int64

In [ ]:
### Q79. Replace multiple values at once.
#here updated marks are previously used function that (marks + 5)
print(df.replace({'marks': {90 : 99 , 80 : 88}}))
print(df.replace([70,60], 77))

  subjects  marks  update_marks
0   python     99            95
1     java     88            85
2      c++     99            95
3     html     70            75
4      css     60            65
  subjects  marks  update_marks
0   python     90            95
1     java     80            85
2      c++     90            95
3     html     77            75
4      css     77            65

In [ ]:
### Q80. Create flag column based on condition.
df['flag']= (df['marks'] >70).astype(int)
print(df["flag"])

0    1
1    1
2    1
3    0
4    0
Name: flag, dtype: int64

🔹 Section 5: Iteration, GroupBy & Pivot (Q81–Q100)

In [ ]:
### Q81. Iterate over rows using `iterrows()`.
for idx , row in df.iterrows():
    print('index : ',idx)
    print("Row Name: ",row['Name'])
    print("Age : ",row['Age'])
    print("Salary : ",row['Salary'])
print(df)

index :  A
Row Name:  Amit
Age :  21
Salary :  25000
index :  B
Row Name:  Priya
Age :  22
Salary :  30000
index :  C
Row Name:  Rahul
Age :  23
Salary :  35000
    Name  Age  Salary
A   Amit   21   25000
B  Priya   22   30000
C  Rahul   23   35000

In [ ]:
### Q82. Iterate using `itertuples()`.
for row in df.itertuples():
    print(row.Name, row.Age , row.Salary )

Amit 21 25000
Priya 22 30000
Rahul 23 35000

In [ ]:
### Q83. Iterate over columns.
for col in df.columns:
    print(df['Name'])

print()
#items() returns a pair:
#Column name
#Column data (Series)
for col , Series in df.items():
    print('Name' , Series)

A     Amit
B    Priya
C    Rahul
Name: Name, dtype: str
A     Amit
B    Priya
C    Rahul
Name: Name, dtype: str
A     Amit
B    Priya
C    Rahul
Name: Name, dtype: str

Name A     Amit
B    Priya
C    Rahul
Name: Name, dtype: str
Name A    21
B    22
C    23
Name: Age, dtype: int64
Name A    25000
B    30000
C    35000
Name: Salary, dtype: int64

In [ ]:
### Q84. Avoid iteration using vectorization.
df5=pd.DataFrame({
    'Name': ['dipali','manas'],
    'age':[22 ,34]
})

df5['new_age']=df5['age']*2+1
print(df5)

df['new_salary']=df['Salary']*2+1
print(df)

     Name  age  new_age
0  dipali   22       45
1   manas   34       69
    Name  Age  Salary  new_salary
A   Amit   21   25000       50001
B  Priya   22   30000       60001
C  Rahul   23   35000       70001

In [ ]:
### Q85. Group data using `groupby()`.
group_mean=df.groupby('Age')['Salary'].mean()
print(group_mean)

Age
21    25000.0
22    30000.0
23    35000.0
Name: Salary, dtype: float64

In [ ]:
### Q86. Calculate sum per group.
group_sum=df.groupby('Age')['Salary'].sum()
print(group_sum)

Age
21    25000
22    30000
23    35000
Name: Salary, dtype: int64

In [ ]:
### Q87. Calculate multiple aggregations.
mul_agg=df.groupby('Age').agg({'Salary' : 'mean', 'Name':'sum'})
print(mul_agg)

for_name=df.groupby('Age').agg(name=('Salary' , 'sum'))
print(for_name)

      Salary   Name
Age
21   25000.0   Amit
22   30000.0  Priya
23   35000.0  Rahul
      name
Age
21   25000
22   30000
23   35000

In [ ]:
### Q88. Group by multiple columns.
mul_col=df.groupby(['Age','Name'])['Salary'].mean()
print(mul_col)

Age  Name
21   Amit     25000.0
22   Priya    30000.0
23   Rahul    35000.0
Name: Salary, dtype: float64

In [ ]:
### Q89. Filter grouped data.
filter_group=df.groupby('Age').filter(lambda g: g['Salary'].mean()>25000)
print(filter_group)

    Name  Age  Salary  new_salary
B  Priya   22   30000       60001
C  Rahul   23   35000       70001

transform() is used when you want to calculate a group statistic (mean, sum, max, etc.) and return a result for every row in the original DataFrame.

In [ ]:
### Q90. Transform grouped data using `transform()`.
trans_gropu=df.groupby('Name')['Age'].transform('mean')
print(trans_gropu)

A    21.0
B    22.0
C    23.0
Name: Age, dtype: float64

In [ ]:
### Q91. Apply custom function in groupby.
custom_group=df.groupby('Name')['Salary'].agg(lambda s: s.max()-s.min())
print(custom_group)

Name
Amit     0
Priya    0
Rahul    0
Name: Salary, dtype: int64

In [ ]:
### Q92. Create basic pivot table.
pivet=pd.pivot_table(df , values='Age' , index='Name',columns='Salary', aggfunc="mean")
print(pivet)

#A pivot table is used to summarize and aggregate data. 
# It is similar to Excel Pivot Tables.

Salary  25000  30000  35000
Name
Amit     21.0    NaN    NaN
Priya     NaN   22.0    NaN
Rahul     NaN    NaN   23.0

In [ ]:
### Q93. Use multiple aggregation functions in pivot.
mul_agg_func=pd.pivot_table(df , values='Salary' , index="Name", columns='Age' , aggfunc=["mean", 'max','min'])
print(mul_agg_func)

          mean                        max                        min           \
Age         21       22       23       21       22       23       21       22
Name
Amit   25000.0      NaN      NaN  25000.0      NaN      NaN  25000.0      NaN
Priya      NaN  30000.0      NaN      NaN  30000.0      NaN      NaN  30000.0
Rahul      NaN      NaN  35000.0      NaN      NaN  35000.0      NaN      NaN


Age         23
Name
Amit       NaN
Priya      NaN
Rahul  35000.0

In [ ]:
### Q94. Handle missing values in pivot tables.
replace_nan=pd.pivot_table(df , values='Age'
                           ,index='Name'
                           ,columns='Salary'
                           , aggfunc='sum'
                           ,fill_value=0)
print(replace_nan)

Salary  25000  30000  35000
Name
Amit       21      0      0
Priya       0     22      0
Rahul       0      0     23

In [ ]:
### Q95. Add margins (totals) in pivot tables.
add_margin=pd.pivot_table(df , values='Age', index='Name',columns='Salary', aggfunc='sum',
                          fill_value=0 , margins=True , 
                          margins_name="Total")
print(add_margin)

Salary  25000  30000  35000  Total
Name
Amit       21      0      0     21
Priya       0     22      0     22
Rahul       0      0     23     23
Total      21     22     23     66

In [ ]:
### Q96. Create multi-level pivot table.
idx_col=pd.pivot_table(df , values='Salary',
                        index=['Age', 'Name'],
                        columns=['Salary','Age'] ,
                          aggfunc='sum')
print(idx_col)

Salary       25000    30000    35000
Age             21       22       23
Age Name
21  Amit   25000.0      NaN      NaN
22  Priya      NaN  30000.0      NaN
23  Rahul      NaN      NaN  35000.0

In [ ]:
### Q97. Convert DataFrame to pivot format.
conver_pivot=df.pivot(index="Name", columns='Age' , values="Salary")
print(conver_pivot)

Age         21       22       23
Name
Amit   25000.0      NaN      NaN
Priya      NaN  30000.0      NaN
Rahul      NaN      NaN  35000.0

groupby() → Best for analysis and aggregation.

pivot_table() → Best for summary reports and can aggregate duplicates.

pivot() → Only reshapes data; it does not aggregate and fails on duplicates.

In [ ]:
### Q98. Compare pivot vs groupby.
group_by=df.groupby('Name')['Salary'].sum()
print(group_by)

#using pivot_table
result=pd.pivot_table(df , values='Salary',
                      index='Name',
                      aggfunc='sum')
print(result)

for_pivot=pd.pivot(df , values='Salary',
                   index='Name',
                   columns='Age')
print(for_pivot)

Name
Amit     25000
Priya    30000
Rahul    35000
Name: Salary, dtype: int64
       Salary
Name
Amit    25000
Priya   30000
Rahul   35000
Age         21       22       23
Name
Amit   25000.0      NaN      NaN
Priya      NaN  30000.0      NaN
Rahul      NaN      NaN  35000.0

In [ ]:
### Q99. Build summary report using pivot table.
combine=pd.pivot_table(df ,values='Age', columns='Name', aggfunc='sum' ,margins=True , fill_value=0).round(2)
convert_csv=df.to_csv(r'C:\Users\HP\Documents\Employee_csv' , index=False)
print(combine)
print(convert_csv)

Name  Amit  All  Priya  All  Rahul  All
Age     21   21     22   22     23   23
None

In [ ]:
### Q100. Create an end-to-end analysis workflow.
df = pd.read_csv('D:\python folder\pandas_practice _folder/Housing.csv')
print(df.head())

#inspect the data
print("===========shape of the Data=======")
print(df.shape)
print("================== data types ==============")
print(df.dtypes)
print("========null values==========")
print(df.isnull().sum())


print()
print("===============clean the Data===========")
print("================fill  null value or nan===========")
#find all numeric columns
#numeric_col=df.select_dtypes(include=['number']).columns
#df=df[numeric_col]=df[numeric_col].fillna(df[numeric_col].mean())
#print(df[numeric_col].isnull().sum())
print(df.fillna(0))
print("============= drop duplicats==========")
print(df.drop_duplicates())

print()
print("================feature engineer===========")
# Feature Engineering
df['price_per_sqft'] = df['price'] / df['area']
print("===============gropu by / pivot analysis============")
print("======group by price area========")
group_data = df.groupby('furnishingstatus')['price'].sum()
print(group_data)
print('========using pivot table========')
pivoted_data=pd.pivot_table(df , 
                            values='price',
                            index='area',
                            columns='furnishingstatus',
                            aggfunc='sum')
print(pivoted_data)
print('===========sorted data=========')
sorted_data=df.sort_values('price',ascending=False)
print(sorted_data)

sorted_data.to_csv('housing_analysis.csv', index=False)
print("analysis completed !")

      price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no
1  12250000  8960         4          4        4      yes        no       no
2  12250000  9960         3          2        2      yes        no      yes
3  12215000  7500         4          2        2      yes        no      yes
4  11410000  7420         4          1        2      yes       yes      yes

  hotwaterheating airconditioning  parking prefarea furnishingstatus
0              no             yes        2      yes        furnished
1              no             yes        3       no        furnished
2              no              no        2      yes   semi-furnished
3              no             yes        3      yes        furnished
4              no             yes        2       no        furnished
===========shape of the Data=======
(545, 13)
================== data types ==============
price               int64
area                int64
bedrooms            int64
bathrooms           int64
stories             int64
mainroad              str
guestroom             str
basement              str
hotwaterheating       str
airconditioning       str
parking             int64
prefarea              str
furnishingstatus      str
dtype: object
========null values==========
price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

===============clean the Data===========
================fill  null value or nan===========
        price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no
1    12250000  8960         4          4        4      yes        no       no
2    12250000  9960         3          2        2      yes        no      yes
3    12215000  7500         4          2        2      yes        no      yes
4    11410000  7420         4          1        2      yes       yes      yes
..        ...   ...       ...        ...      ...      ...       ...      ...
540   1820000  3000         2          1        1      yes        no      yes
541   1767150  2400         3          1        1       no        no       no
542   1750000  3620         2          1        1      yes        no       no
543   1750000  2910         3          1        1       no        no       no
544   1750000  3850         3          1        2      yes        no       no

    hotwaterheating airconditioning  parking prefarea furnishingstatus
0                no             yes        2      yes        furnished
1                no             yes        3       no        furnished
2                no              no        2      yes   semi-furnished
3                no             yes        3      yes        furnished
4                no             yes        2       no        furnished
..              ...             ...      ...      ...              ...
540              no              no        2       no      unfurnished
541              no              no        0       no   semi-furnished
542              no              no        0       no      unfurnished
543              no              no        0       no        furnished
544              no              no        0       no      unfurnished

[545 rows x 13 columns]
============= drop duplicats==========
        price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no
1    12250000  8960         4          4        4      yes        no       no
2    12250000  9960         3          2        2      yes        no      yes
3    12215000  7500         4          2        2      yes        no      yes
4    11410000  7420         4          1        2      yes       yes      yes
..        ...   ...       ...        ...      ...      ...       ...      ...
540   1820000  3000         2          1        1      yes        no      yes
541   1767150  2400         3          1        1       no        no       no
542   1750000  3620         2          1        1      yes        no       no
543   1750000  2910         3          1        1       no        no       no
544   1750000  3850         3          1        2      yes        no       no

    hotwaterheating airconditioning  parking prefarea furnishingstatus
0                no             yes        2      yes        furnished
1                no             yes        3       no        furnished
2                no              no        2      yes   semi-furnished
3                no             yes        3      yes        furnished
4                no             yes        2       no        furnished
..              ...             ...      ...      ...              ...
540              no              no        2       no      unfurnished
541              no              no        0       no   semi-furnished
542              no              no        0       no      unfurnished
543              no              no        0       no        furnished
544              no              no        0       no      unfurnished

[545 rows x 13 columns]

================feature engineer===========
===============gropu by / pivot analysis============
======group by price area========
furnishingstatus
furnished          769397440
semi-furnished    1114008000
unfurnished        714462000
Name: price, dtype: int64
========using pivot table========
furnishingstatus   furnished  semi-furnished  unfurnished
area
1650                     NaN             NaN    3150000.0
1700                     NaN             NaN    1890000.0
1836                     NaN       2275000.0          NaN
1905                     NaN       4340000.0          NaN
1950                     NaN             NaN    5670000.0
...                      ...             ...          ...
12900              4900000.0             NaN          NaN
12944                    NaN             NaN    3500000.0
13200             16730000.0             NaN          NaN
15600                    NaN       5943000.0          NaN
16200                    NaN             NaN   10150000.0

[284 rows x 3 columns]
===========sorted data=========
        price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no
1    12250000  8960         4          4        4      yes        no       no
2    12250000  9960         3          2        2      yes        no      yes
3    12215000  7500         4          2        2      yes        no      yes
4    11410000  7420         4          1        2      yes       yes      yes
..        ...   ...       ...        ...      ...      ...       ...      ...
540   1820000  3000         2          1        1      yes        no      yes
541   1767150  2400         3          1        1       no        no       no
542   1750000  3620         2          1        1      yes        no       no
543   1750000  2910         3          1        1       no        no       no
544   1750000  3850         3          1        2      yes        no       no

    hotwaterheating airconditioning  parking prefarea furnishingstatus  \
0                no             yes        2      yes        furnished
1                no             yes        3       no        furnished
2                no              no        2      yes   semi-furnished
3                no             yes        3      yes        furnished
4                no             yes        2       no        furnished
..              ...             ...      ...      ...              ...
540              no              no        2       no      unfurnished
541              no              no        0       no   semi-furnished
542              no              no        0       no      unfurnished
543              no              no        0       no        furnished
544              no              no        0       no      unfurnished

     price_per_sqft
0       1792.452830
1       1367.187500
2       1229.919679
3       1628.666667
4       1537.735849
..              ...
540      606.666667
541      736.312500
542      483.425414
543      601.374570
544      454.545455

[545 rows x 14 columns]
analysis completed !

<>:2: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
<>:2: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
C:\Users\HP\AppData\Local\Temp\ipykernel_2348\1100773706.py:2: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
  df = pd.read_csv('D:\python folder\pandas_practice _folder/Housing.csv')

In [ ]:
print(df.columns.tolist())

['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'parking', 'price_per_sqft']

## 🔹 Section 1: Basics & Series (Q1–Q20)

In [ ]:
### Q1. Create a Pandas Series from a list of integers.
se=pd.Series([[1,2,3,4,5],[6,7,8,9,10]])
se

0     [1, 2, 3, 4, 5]
1    [6, 7, 8, 9, 10]
dtype: object

In [ ]:
### Q2. Create a Series from a dictionary with custom index.
stude_name={
   'Dipali':20,'Anu':19,'manas':18
}

dic=pd.Series(stude_name,index=['Dipali','Anu','manas'])

In [ ]:
data={
    'name':['di','ni','chi'],
    'age':[20,21,22],
    'city':['mumbai','pune','delhi']
}
df=pd.DataFrame(data)
print(df)
#df.to_csv("Output.csv",indxe=False)
#df.to_excel("outpu.xlxs",index=False)
df.to_json("outpu.json",index=False)

  name  age    city
0   di   20  mumbai
1   ni   21    pune
2  chi   22   delhi

NumPy Interview Coding Questions (Beginner)

In [ ]:
arr=np.array([10, 20, 30, 40])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
#3. Find maximum and minimum element.
print(arr.min())
print(np.min(arr))
print(arr.max())
print(np.max(arr))

#4. Find second largest element.
#using sort
second=np.sort(arr)[-2]
print(second)
#using partition
second1=np.partition(arr , -2)[-2]
print(second1)
#Method 3: Handle Duplicates
second3=np.unique(arr)[-2]
print(second3)

(4,)
4
1
int64
10
10
40
40
30
30
30

In [ ]:
#4. Find second largest element.
arr = np.array([[10, 25, 8],
                [45, 15, 30]])

#flat=arr.flatten()
print(np.sort(arr)[-2])
#Shortcut
second=np.sort(arr , axis=None)[-2]
print(second)

#2. Second Largest in the Entire 3D Array
arr = np.array([
    [[1, 8], [3, 4]],
    [[9, 6], [7, 2]]
])

secn=np.sort(arr , axis=None)[-2]
print(secn)
#if arr has duplicates
second_large=np.unique(arr)[-2]
print(second_large)

##4. Second Largest in Each Row
second_lar=np.sort(arr , axis=1)[:,-2]
print(second_lar)

##4. Second Largest in Each column
second_lar=np.sort(arr , axis=0)[:,-2]
print(second_lar)

#for better efficiency
lasrge=np.partition(arr , -2 , axis=None)[-2]
print(lasrge)

[ 8 10 25]
30
8
8
[[1 4]
 [7 2]]
[[1 6]
 [9 8]]
8

In [ ]:
#5. Find third largest element.
arr = np.array([[10, 25, 8,8],
                [45, 15, 30,30]])
flat=arr.flatten()
third_large=np.sort(flat)[-3]
print(third_large)

#6. Reverse an array.
rev=arr[::-1]
print(rev)

#7. Sort an array.
sor=np.sort(arr)
print(sor)

#8. Find unique elements.
print(np.unique(arr))

#9. Count frequency of each element.
uniqu , count=np.unique(arr , return_counts=True)
print("unique  :",uniqu)
print("count : ",count)

#Display as Element : Frequency
for i in range(len(uniqu)):
    print(uniqu[i], ":",count[i])

#Method 2: Using a Dictionary (Without np.unique())
arr = np.array([1, 2, 2, 3, 3, 3, 4])
freq={}
for i in arr : 
    if i in freq:
        freq[i]+=1
    else:
        freq[i]=1
print(freq)

30
[[45 15 30 30]
 [10 25  8  8]]
[[ 8  8 10 25]
 [15 30 30 45]]
[ 8 10 15 25 30 45]
unique  : [ 8 10 15 25 30 45]
count :  [2 1 1 1 2 1]
8 : 2
10 : 1
15 : 1
25 : 1
30 : 2
45 : 1
{np.int64(1): 1, np.int64(2): 2, np.int64(3): 3, np.int64(4): 1}

In [ ]:
#Method 3: For a 2D Array
arr = np.array([[1, 2, 2],
                [3, 3, 4]])
uniqu , count=np.unique(arr , return_counts=True)
for u ,c in zip(uniqu, count):
    print(u , ":",c)

1 : 1
2 : 2
3 : 2
4 : 1

In [ ]:
#10. Find even and odd numbers.
import numpy as np
arr=np.array([[1,np.nan,3,4,5],
              [6,7,8,np.nan,10]])
#falt=arr.flatten()
#for i in falt:
 #   if i%2==0:
  #      print(i)


#using numpy
even=arr[arr%2==0]
print(even)

[ 4.  6.  8. 10.]

In [ ]:
#11. Replace all even numbers with 0.
even=arr[arr%2==0]=0
print(arr)

[[ 1. nan  3.  0.  5.]
 [ 0.  7.  0. nan  0.]]

In [ ]:
#12. Replace all negative values with NaN.
arr1=np.array([[-1,2,3,-4,5],
               [-6,7,-8,9,10]], dtype=float)
negative=arr1[arr1 < 0] = np.nan
print(arr1)

[[nan  2.  3. nan  5.]
 [nan  7. nan  9. 10.]]

In [ ]:
#13. Merge two arrays.
arr1=np.arange(1,10)
print(arr1)
arr2=np.arange(11,20)
print(arr2)
arr3 = np.concatenate((arr1,arr2))
print(arr3)
#Using np.hstack()
arr4=np.hstack((arr1 , arr3))
print(arr4)

[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[ 1  2  3  4  5  6  7  8  9  1  2  3  4  5  6  7  8  9 11 12 13 14 15 16
 17 18 19]

why doble parenthesis?


Outer () → function call

Inner () → tuple containing the arrays